ChatMessage[] messages            # List of chat messages
string grammar
string json_schema
bool add_generation_prompt
bool use_jinja
ChatTool[] tools
int32 tool_choice
bool extract_reasoning
SamplingConfig sampling_config
sensor_msgs/Image image
---
string id
Choice[] choices
int32 created
string model
string object "chat.completion"
string system_fingerprint
UsageStats usage
---
PartialResponse partial_response    # partial response