var searchData=
[
  ['samplingconfig_0',['&lt;span class=&quot;tt&quot;&gt;SamplingConfig&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/SamplingConfig&lt;/span&gt;)',['../index.html#autotoc_md45',1,'']]],
  ['samplingconfig_20llama_5fmsgs_20msg_20samplingconfig_1',['&lt;span class=&quot;tt&quot;&gt;SamplingConfig&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/SamplingConfig&lt;/span&gt;)',['../index.html#autotoc_md45',1,'']]],
  ['samplinginfo_2',['&lt;span class=&quot;tt&quot;&gt;SamplingInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/SamplingInfo&lt;/span&gt;)',['../index.html#autotoc_md62',1,'']]],
  ['samplinginfo_20llama_5fmsgs_20msg_20samplinginfo_3',['&lt;span class=&quot;tt&quot;&gt;SamplingInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/SamplingInfo&lt;/span&gt;)',['../index.html#autotoc_md62',1,'']]],
  ['services_4',['Services',['../index.html#autotoc_md81',1,'']]],
  ['shards_5',['llama_ros (YAML Config + model shards)',['../index.html#autotoc_md12',1,'']]],
  ['simple_20speculative_20ngram_5fsimple_6',['Ngram-simple (&lt;span class=&quot;tt&quot;&gt;speculative.ngram_simple.*&lt;/span&gt;)',['../index.html#autotoc_md38',1,'']]],
  ['slots_20demo_7',['Parallel Slots Demo',['../index.html#autotoc_md138',1,'']]],
  ['speculative_8',['Speculative Decoding (&lt;span class=&quot;tt&quot;&gt;speculative.*&lt;/span&gt;)',['../index.html#autotoc_md34',1,'']]],
  ['speculative_20decoding_9',['llama_ros (Speculative Decoding)',['../index.html#autotoc_md13',1,'']]],
  ['speculative_20decoding_20demo_10',['Speculative Decoding Demo',['../index.html#autotoc_md117',1,'MTP Speculative Decoding Demo'],['../index.html#autotoc_md116',1,'Speculative Decoding Demo']]],
  ['speculative_20decoding_20speculative_11',['Speculative Decoding (&lt;span class=&quot;tt&quot;&gt;speculative.*&lt;/span&gt;)',['../index.html#autotoc_md34',1,'']]],
  ['speculative_20draft_12',['Draft Model (&lt;span class=&quot;tt&quot;&gt;speculative.draft.*&lt;/span&gt;)',['../index.html#autotoc_md35',1,'']]],
  ['speculative_20draft_20cpu_20and_20speculative_20draft_20cpu_5fbatch_13',['Draft CPU (&lt;span class=&quot;tt&quot;&gt;speculative.draft.cpu.*&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;speculative.draft.cpu_batch.*&lt;/span&gt;)',['../index.html#autotoc_md36',1,'']]],
  ['speculative_20draft_20cpu_5fbatch_14',['Draft CPU (&lt;span class=&quot;tt&quot;&gt;speculative.draft.cpu.*&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;speculative.draft.cpu_batch.*&lt;/span&gt;)',['../index.html#autotoc_md36',1,'']]],
  ['speculative_20ngram_5fcache_15',['Ngram-cache (&lt;span class=&quot;tt&quot;&gt;speculative.ngram_cache.*&lt;/span&gt;)',['../index.html#autotoc_md41',1,'']]],
  ['speculative_20ngram_5fmap_5fk_16',['Ngram-map-k (&lt;span class=&quot;tt&quot;&gt;speculative.ngram_map_k.*&lt;/span&gt;)',['../index.html#autotoc_md39',1,'']]],
  ['speculative_20ngram_5fmap_5fk4v_17',['Ngram-map-k4v (&lt;span class=&quot;tt&quot;&gt;speculative.ngram_map_k4v.*&lt;/span&gt;)',['../index.html#autotoc_md40',1,'']]],
  ['speculative_20ngram_5fmod_18',['Ngram-mod (&lt;span class=&quot;tt&quot;&gt;speculative.ngram_mod.*&lt;/span&gt;)',['../index.html#autotoc_md37',1,'']]],
  ['speculative_20ngram_5fsimple_19',['Ngram-simple (&lt;span class=&quot;tt&quot;&gt;speculative.ngram_simple.*&lt;/span&gt;)',['../index.html#autotoc_md38',1,'']]],
  ['srv_20detokenize_20',['&lt;span class=&quot;tt&quot;&gt;Detokenize&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/srv/Detokenize&lt;/span&gt;)',['../index.html#autotoc_md83',1,'']]],
  ['srv_20evaluatedecisions_21',['&lt;span class=&quot;tt&quot;&gt;EvaluateDecisions&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/srv/EvaluateDecisions&lt;/span&gt;)',['../index.html#autotoc_md89',1,'']]],
  ['srv_20generateembeddings_22',['&lt;span class=&quot;tt&quot;&gt;GenerateEmbeddings&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/srv/GenerateEmbeddings&lt;/span&gt;)',['../index.html#autotoc_md84',1,'']]],
  ['srv_20getmetadata_23',['&lt;span class=&quot;tt&quot;&gt;GetMetadata&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/srv/GetMetadata&lt;/span&gt;)',['../index.html#autotoc_md86',1,'']]],
  ['srv_20listloras_24',['&lt;span class=&quot;tt&quot;&gt;ListLoRAs&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/srv/ListLoRAs&lt;/span&gt;)',['../index.html#autotoc_md87',1,'']]],
  ['srv_20rerankdocuments_25',['&lt;span class=&quot;tt&quot;&gt;RerankDocuments&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/srv/RerankDocuments&lt;/span&gt;)',['../index.html#autotoc_md85',1,'']]],
  ['srv_20tokenize_26',['&lt;span class=&quot;tt&quot;&gt;Tokenize&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/srv/Tokenize&lt;/span&gt;)',['../index.html#autotoc_md82',1,'']]],
  ['srv_20updateloras_27',['&lt;span class=&quot;tt&quot;&gt;UpdateLoRAs&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/srv/UpdateLoRAs&lt;/span&gt;)',['../index.html#autotoc_md88',1,'']]],
  ['stream_28',['Stream',['../index.html#autotoc_md103',1,'llama_ros (Stream)'],['../index.html#autotoc_md123',1,'RAG Demo (LLM + chat template + RAG + Reranking + Stream)']]],
  ['streaming_20tools_20demo_29',['Streaming Tools Demo',['../index.html#autotoc_md133',1,'']]],
  ['structured_20output_30',['chat_llama_ros (Structured output)',['../index.html#autotoc_md110',1,'']]],
  ['structured_20output_20demo_31',['Chat Structured Output Demo',['../index.html#autotoc_md131',1,'']]]
];
