var searchData=
[
  ['langchain_0',['LangChain',['../index.html#autotoc_md101',1,'']]],
  ['launch_1',['Launch',['../index.html#autotoc_md10',1,'llama_ros (Python Launch)'],['../index.html#autotoc_md14',1,'llava_ros (Python Launch)']]],
  ['launch_2',['launch',['../index.html#autotoc_md7',1,'']]],
  ['launch_20files_3',['Launch Files',['../index.html#autotoc_md9',1,'']]],
  ['listloras_4',['&lt;span class=&quot;tt&quot;&gt;ListLoRAs&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/srv/ListLoRAs&lt;/span&gt;)',['../index.html#autotoc_md87',1,'']]],
  ['listloras_20llama_5fmsgs_20srv_20listloras_5',['&lt;span class=&quot;tt&quot;&gt;ListLoRAs&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/srv/ListLoRAs&lt;/span&gt;)',['../index.html#autotoc_md87',1,'']]],
  ['llama_5fcli_6',['llama_cli',['../index.html#autotoc_md6',1,'']]],
  ['llama_5fmsgs_20action_20generatechatcompletions_7',['llama_msgs action GenerateChatCompletions',['../index.html#autotoc_md74',1,'&lt;span class=&quot;tt&quot;&gt;GenerateChatCompletions&lt;/span&gt; Feedback (&lt;span class=&quot;tt&quot;&gt;llama_msgs/action/GenerateChatCompletions&lt;/span&gt;)'],['../index.html#autotoc_md71',1,'&lt;span class=&quot;tt&quot;&gt;GenerateChatCompletions&lt;/span&gt; Goal (&lt;span class=&quot;tt&quot;&gt;llama_msgs/action/GenerateChatCompletions&lt;/span&gt;)'],['../index.html#autotoc_md72',1,'&lt;span class=&quot;tt&quot;&gt;GenerateChatCompletions&lt;/span&gt; Result (&lt;span class=&quot;tt&quot;&gt;llama_msgs/action/GenerateChatCompletions&lt;/span&gt;)']]],
  ['llama_5fmsgs_20action_20generateresponse_8',['llama_msgs action GenerateResponse',['../index.html#autotoc_md79',1,'&lt;span class=&quot;tt&quot;&gt;GenerateResponse&lt;/span&gt; Feedback (&lt;span class=&quot;tt&quot;&gt;llama_msgs/action/GenerateResponse&lt;/span&gt;)'],['../index.html#autotoc_md77',1,'&lt;span class=&quot;tt&quot;&gt;GenerateResponse&lt;/span&gt; Goal (&lt;span class=&quot;tt&quot;&gt;llama_msgs/action/GenerateResponse&lt;/span&gt;)'],['../index.html#autotoc_md78',1,'&lt;span class=&quot;tt&quot;&gt;GenerateResponse&lt;/span&gt; Result (&lt;span class=&quot;tt&quot;&gt;llama_msgs/action/GenerateResponse&lt;/span&gt;)']]],
  ['llama_5fmsgs_20msg_20attentioninfo_9',['&lt;span class=&quot;tt&quot;&gt;AttentionInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/AttentionInfo&lt;/span&gt;)',['../index.html#autotoc_md58',1,'']]],
  ['llama_5fmsgs_20msg_20basemodelinfo_10',['&lt;span class=&quot;tt&quot;&gt;BaseModelInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/BaseModelInfo&lt;/span&gt;)',['../index.html#autotoc_md61',1,'']]],
  ['llama_5fmsgs_20msg_20chatchoice_11',['&lt;span class=&quot;tt&quot;&gt;ChatChoice&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatChoice&lt;/span&gt;)',['../index.html#autotoc_md73',1,'']]],
  ['llama_5fmsgs_20msg_20chatchoicechunk_12',['&lt;span class=&quot;tt&quot;&gt;ChatChoiceChunk&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatChoiceChunk&lt;/span&gt;)',['../index.html#autotoc_md75',1,'']]],
  ['llama_5fmsgs_20msg_20chatcontent_13',['&lt;span class=&quot;tt&quot;&gt;ChatContent&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatContent&lt;/span&gt;)',['../index.html#autotoc_md50',1,'']]],
  ['llama_5fmsgs_20msg_20chatdeltachunk_14',['&lt;span class=&quot;tt&quot;&gt;ChatDeltaChunk&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatDeltaChunk&lt;/span&gt;)',['../index.html#autotoc_md76',1,'']]],
  ['llama_5fmsgs_20msg_20chatmessage_15',['&lt;span class=&quot;tt&quot;&gt;ChatMessage&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatMessage&lt;/span&gt;)',['../index.html#autotoc_md49',1,'']]],
  ['llama_5fmsgs_20msg_20chatreasoningformat_16',['&lt;span class=&quot;tt&quot;&gt;ChatReasoningFormat&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatReasoningFormat&lt;/span&gt;)',['../index.html#autotoc_md54',1,'']]],
  ['llama_5fmsgs_20msg_20chatreqtool_17',['&lt;span class=&quot;tt&quot;&gt;ChatReqTool&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatReqTool&lt;/span&gt;)',['../index.html#autotoc_md52',1,'']]],
  ['llama_5fmsgs_20msg_20chattool_18',['&lt;span class=&quot;tt&quot;&gt;ChatTool&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatTool&lt;/span&gt;)',['../index.html#autotoc_md53',1,'']]],
  ['llama_5fmsgs_20msg_20chattoolcall_19',['&lt;span class=&quot;tt&quot;&gt;ChatToolCall&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatToolCall&lt;/span&gt;)',['../index.html#autotoc_md51',1,'']]],
  ['llama_5fmsgs_20msg_20decisionanswer_20',['&lt;span class=&quot;tt&quot;&gt;DecisionAnswer&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/DecisionAnswer&lt;/span&gt;)',['../index.html#autotoc_md65',1,'']]],
  ['llama_5fmsgs_20msg_20decisioninfo_21',['&lt;span class=&quot;tt&quot;&gt;DecisionInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/DecisionInfo&lt;/span&gt;)',['../index.html#autotoc_md63',1,'']]],
  ['llama_5fmsgs_20msg_20decisionquestion_22',['&lt;span class=&quot;tt&quot;&gt;DecisionQuestion&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/DecisionQuestion&lt;/span&gt;)',['../index.html#autotoc_md64',1,'']]],
  ['llama_5fmsgs_20msg_20generalinfo_23',['&lt;span class=&quot;tt&quot;&gt;GeneralInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/GeneralInfo&lt;/span&gt;)',['../index.html#autotoc_md56',1,'']]],
  ['llama_5fmsgs_20msg_20grammartrigger_24',['&lt;span class=&quot;tt&quot;&gt;GrammarTrigger&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/GrammarTrigger&lt;/span&gt;)',['../index.html#autotoc_md48',1,'']]],
  ['llama_5fmsgs_20msg_20logitbias_25',['&lt;span class=&quot;tt&quot;&gt;LogitBias&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LogitBias&lt;/span&gt;)',['../index.html#autotoc_md46',1,'']]],
  ['llama_5fmsgs_20msg_20logitbiasarray_26',['&lt;span class=&quot;tt&quot;&gt;LogitBiasArray&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LogitBiasArray&lt;/span&gt;)',['../index.html#autotoc_md47',1,'']]],
  ['llama_5fmsgs_20msg_20lora_27',['&lt;span class=&quot;tt&quot;&gt;LoRA&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LoRA&lt;/span&gt;)',['../index.html#autotoc_md80',1,'']]],
  ['llama_5fmsgs_20msg_20metadata_28',['&lt;span class=&quot;tt&quot;&gt;Metadata&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/Metadata&lt;/span&gt;)',['../index.html#autotoc_md55',1,'']]],
  ['llama_5fmsgs_20msg_20modelinfo_29',['&lt;span class=&quot;tt&quot;&gt;ModelInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ModelInfo&lt;/span&gt;)',['../index.html#autotoc_md57',1,'']]],
  ['llama_5fmsgs_20msg_20partialresponse_30',['&lt;span class=&quot;tt&quot;&gt;PartialResponse&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/PartialResponse&lt;/span&gt;)',['../index.html#autotoc_md67',1,'']]],
  ['llama_5fmsgs_20msg_20response_31',['&lt;span class=&quot;tt&quot;&gt;Response&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/Response&lt;/span&gt;)',['../index.html#autotoc_md66',1,'']]],
  ['llama_5fmsgs_20msg_20ropeinfo_32',['&lt;span class=&quot;tt&quot;&gt;RoPEInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/RoPEInfo&lt;/span&gt;)',['../index.html#autotoc_md59',1,'']]],
  ['llama_5fmsgs_20msg_20samplingconfig_33',['&lt;span class=&quot;tt&quot;&gt;SamplingConfig&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/SamplingConfig&lt;/span&gt;)',['../index.html#autotoc_md45',1,'']]],
  ['llama_5fmsgs_20msg_20samplinginfo_34',['&lt;span class=&quot;tt&quot;&gt;SamplingInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/SamplingInfo&lt;/span&gt;)',['../index.html#autotoc_md62',1,'']]],
  ['llama_5fmsgs_20msg_20tokenizerinfo_35',['&lt;span class=&quot;tt&quot;&gt;TokenizerInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/TokenizerInfo&lt;/span&gt;)',['../index.html#autotoc_md60',1,'']]],
  ['llama_5fmsgs_20msg_20tokenprob_36',['&lt;span class=&quot;tt&quot;&gt;TokenProb&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/TokenProb&lt;/span&gt;)',['../index.html#autotoc_md68',1,'']]],
  ['llama_5fmsgs_20msg_20tokenprobarray_37',['&lt;span class=&quot;tt&quot;&gt;TokenProbArray&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/TokenProbArray&lt;/span&gt;)',['../index.html#autotoc_md69',1,'']]],
  ['llama_5fmsgs_20msg_20usagestats_38',['&lt;span class=&quot;tt&quot;&gt;UsageStats&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/UsageStats&lt;/span&gt;)',['../index.html#autotoc_md70',1,'']]],
  ['llama_5fmsgs_20srv_20detokenize_39',['&lt;span class=&quot;tt&quot;&gt;Detokenize&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/srv/Detokenize&lt;/span&gt;)',['../index.html#autotoc_md83',1,'']]],
  ['llama_5fmsgs_20srv_20evaluatedecisions_40',['&lt;span class=&quot;tt&quot;&gt;EvaluateDecisions&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/srv/EvaluateDecisions&lt;/span&gt;)',['../index.html#autotoc_md89',1,'']]],
  ['llama_5fmsgs_20srv_20generateembeddings_41',['&lt;span class=&quot;tt&quot;&gt;GenerateEmbeddings&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/srv/GenerateEmbeddings&lt;/span&gt;)',['../index.html#autotoc_md84',1,'']]],
  ['llama_5fmsgs_20srv_20getmetadata_42',['&lt;span class=&quot;tt&quot;&gt;GetMetadata&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/srv/GetMetadata&lt;/span&gt;)',['../index.html#autotoc_md86',1,'']]],
  ['llama_5fmsgs_20srv_20listloras_43',['&lt;span class=&quot;tt&quot;&gt;ListLoRAs&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/srv/ListLoRAs&lt;/span&gt;)',['../index.html#autotoc_md87',1,'']]],
  ['llama_5fmsgs_20srv_20rerankdocuments_44',['&lt;span class=&quot;tt&quot;&gt;RerankDocuments&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/srv/RerankDocuments&lt;/span&gt;)',['../index.html#autotoc_md85',1,'']]],
  ['llama_5fmsgs_20srv_20tokenize_45',['&lt;span class=&quot;tt&quot;&gt;Tokenize&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/srv/Tokenize&lt;/span&gt;)',['../index.html#autotoc_md82',1,'']]],
  ['llama_5fmsgs_20srv_20updateloras_46',['&lt;span class=&quot;tt&quot;&gt;UpdateLoRAs&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/srv/UpdateLoRAs&lt;/span&gt;)',['../index.html#autotoc_md88',1,'']]],
  ['llama_5fros_47',['llama_ros',['../index.html',1,'']]],
  ['llama_5fros_20chain_48',['llama_ros (Chain)',['../index.html#autotoc_md102',1,'']]],
  ['llama_5fros_20llm_20rag_20reranker_49',['llama_ros (LLM + RAG + Reranker)',['../index.html#autotoc_md107',1,'']]],
  ['llama_5fros_20python_20launch_50',['llama_ros (Python Launch)',['../index.html#autotoc_md10',1,'']]],
  ['llama_5fros_20reranker_51',['llama_ros (Reranker)',['../index.html#autotoc_md106',1,'']]],
  ['llama_5fros_20speculative_20decoding_52',['llama_ros (Speculative Decoding)',['../index.html#autotoc_md13',1,'']]],
  ['llama_5fros_20stream_53',['llama_ros (Stream)',['../index.html#autotoc_md103',1,'']]],
  ['llama_5fros_20yaml_20config_54',['llama_ros (YAML Config)',['../index.html#autotoc_md11',1,'']]],
  ['llama_5fros_20yaml_20config_20model_20shards_55',['llama_ros (YAML Config + model shards)',['../index.html#autotoc_md12',1,'']]],
  ['llama_5fros_5fembeddings_20rag_56',['llama_ros_embeddings (RAG)',['../index.html#autotoc_md105',1,'']]],
  ['llava_57',['Generate Response (llava)',['../index.html#autotoc_md97',1,'']]],
  ['llava_5fros_58',['llava_ros',['../index.html#autotoc_md104',1,'']]],
  ['llava_5fros_20audio_59',['llava_ros (Audio)',['../index.html#autotoc_md16',1,'']]],
  ['llava_5fros_20python_20launch_60',['llava_ros (Python Launch)',['../index.html#autotoc_md14',1,'']]],
  ['llava_5fros_20yaml_20config_61',['llava_ros (YAML Config)',['../index.html#autotoc_md15',1,'']]],
  ['llm_20chat_20template_20rag_20reranking_20stream_62',['RAG Demo (LLM + chat template + RAG + Reranking + Stream)',['../index.html#autotoc_md123',1,'']]],
  ['llm_20demo_63',['LLM Demo',['../index.html#autotoc_md115',1,'']]],
  ['llm_20rag_20reranker_64',['llama_ros (LLM + RAG + Reranker)',['../index.html#autotoc_md107',1,'']]],
  ['logitbias_65',['&lt;span class=&quot;tt&quot;&gt;LogitBias&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LogitBias&lt;/span&gt;)',['../index.html#autotoc_md46',1,'']]],
  ['logitbias_20llama_5fmsgs_20msg_20logitbias_66',['&lt;span class=&quot;tt&quot;&gt;LogitBias&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LogitBias&lt;/span&gt;)',['../index.html#autotoc_md46',1,'']]],
  ['logitbiasarray_67',['&lt;span class=&quot;tt&quot;&gt;LogitBiasArray&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LogitBiasArray&lt;/span&gt;)',['../index.html#autotoc_md47',1,'']]],
  ['logitbiasarray_20llama_5fmsgs_20msg_20logitbiasarray_68',['&lt;span class=&quot;tt&quot;&gt;LogitBiasArray&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LogitBiasArray&lt;/span&gt;)',['../index.html#autotoc_md47',1,'']]],
  ['lora_69',['&lt;span class=&quot;tt&quot;&gt;LoRA&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LoRA&lt;/span&gt;)',['../index.html#autotoc_md80',1,'']]],
  ['lora_70',['LoRA Adapters (&lt;span class=&quot;tt&quot;&gt;lora.*&lt;/span&gt;)',['../index.html#autotoc_md43',1,'']]],
  ['lora_20adapters_71',['LoRA Adapters',['../index.html#autotoc_md90',1,'']]],
  ['lora_20adapters_20lora_72',['LoRA Adapters (&lt;span class=&quot;tt&quot;&gt;lora.*&lt;/span&gt;)',['../index.html#autotoc_md43',1,'']]],
  ['lora_20llama_5fmsgs_20msg_20lora_73',['&lt;span class=&quot;tt&quot;&gt;LoRA&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LoRA&lt;/span&gt;)',['../index.html#autotoc_md80',1,'']]]
];
