var searchData=
[
  ['map_20k_20speculative_20ngram_5fmap_5fk_0',['Ngram-map-k (&lt;span class=&quot;tt&quot;&gt;speculative.ngram_map_k.*&lt;/span&gt;)',['../index.html#autotoc_md39',1,'']]],
  ['map_20k4v_20speculative_20ngram_5fmap_5fk4v_1',['Ngram-map-k4v (&lt;span class=&quot;tt&quot;&gt;speculative.ngram_map_k4v.*&lt;/span&gt;)',['../index.html#autotoc_md40',1,'']]],
  ['memory_2',['Memory (&lt;span class=&quot;tt&quot;&gt;memory.*&lt;/span&gt;)',['../index.html#autotoc_md26',1,'']]],
  ['memory_20memory_3',['Memory (&lt;span class=&quot;tt&quot;&gt;memory.*&lt;/span&gt;)',['../index.html#autotoc_md26',1,'']]],
  ['messages_4',['Messages',['../index.html#autotoc_md44',1,'']]],
  ['metadata_5',['Metadata',['../index.html#autotoc_md55',1,'&lt;span class=&quot;tt&quot;&gt;Metadata&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/Metadata&lt;/span&gt;)'],['../index.html#autotoc_md99',1,'Get Metadata']]],
  ['metadata_20llama_5fmsgs_20msg_20metadata_6',['&lt;span class=&quot;tt&quot;&gt;Metadata&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/Metadata&lt;/span&gt;)',['../index.html#autotoc_md55',1,'']]],
  ['mmproj_7',['Multimodal Projector (&lt;span class=&quot;tt&quot;&gt;mmproj.*&lt;/span&gt;)',['../index.html#autotoc_md20',1,'']]],
  ['mod_20speculative_20ngram_5fmod_8',['Ngram-mod (&lt;span class=&quot;tt&quot;&gt;speculative.ngram_mod.*&lt;/span&gt;)',['../index.html#autotoc_md37',1,'']]],
  ['model_9',['Model (&lt;span class=&quot;tt&quot;&gt;model.*&lt;/span&gt;)',['../index.html#autotoc_md19',1,'']]],
  ['model_20model_10',['Model (&lt;span class=&quot;tt&quot;&gt;model.*&lt;/span&gt;)',['../index.html#autotoc_md19',1,'']]],
  ['model_20overrides_11',['Model Overrides',['../index.html#autotoc_md23',1,'']]],
  ['model_20shards_12',['llama_ros (YAML Config + model shards)',['../index.html#autotoc_md12',1,'']]],
  ['model_20speculative_20draft_13',['Draft Model (&lt;span class=&quot;tt&quot;&gt;speculative.draft.*&lt;/span&gt;)',['../index.html#autotoc_md35',1,'']]],
  ['modelinfo_14',['&lt;span class=&quot;tt&quot;&gt;ModelInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ModelInfo&lt;/span&gt;)',['../index.html#autotoc_md57',1,'']]],
  ['modelinfo_20llama_5fmsgs_20msg_20modelinfo_15',['&lt;span class=&quot;tt&quot;&gt;ModelInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ModelInfo&lt;/span&gt;)',['../index.html#autotoc_md57',1,'']]],
  ['msg_20attentioninfo_16',['&lt;span class=&quot;tt&quot;&gt;AttentionInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/AttentionInfo&lt;/span&gt;)',['../index.html#autotoc_md58',1,'']]],
  ['msg_20basemodelinfo_17',['&lt;span class=&quot;tt&quot;&gt;BaseModelInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/BaseModelInfo&lt;/span&gt;)',['../index.html#autotoc_md61',1,'']]],
  ['msg_20chatchoice_18',['&lt;span class=&quot;tt&quot;&gt;ChatChoice&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatChoice&lt;/span&gt;)',['../index.html#autotoc_md73',1,'']]],
  ['msg_20chatchoicechunk_19',['&lt;span class=&quot;tt&quot;&gt;ChatChoiceChunk&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatChoiceChunk&lt;/span&gt;)',['../index.html#autotoc_md75',1,'']]],
  ['msg_20chatcontent_20',['&lt;span class=&quot;tt&quot;&gt;ChatContent&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatContent&lt;/span&gt;)',['../index.html#autotoc_md50',1,'']]],
  ['msg_20chatdeltachunk_21',['&lt;span class=&quot;tt&quot;&gt;ChatDeltaChunk&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatDeltaChunk&lt;/span&gt;)',['../index.html#autotoc_md76',1,'']]],
  ['msg_20chatmessage_22',['&lt;span class=&quot;tt&quot;&gt;ChatMessage&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatMessage&lt;/span&gt;)',['../index.html#autotoc_md49',1,'']]],
  ['msg_20chatreasoningformat_23',['&lt;span class=&quot;tt&quot;&gt;ChatReasoningFormat&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatReasoningFormat&lt;/span&gt;)',['../index.html#autotoc_md54',1,'']]],
  ['msg_20chatreqtool_24',['&lt;span class=&quot;tt&quot;&gt;ChatReqTool&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatReqTool&lt;/span&gt;)',['../index.html#autotoc_md52',1,'']]],
  ['msg_20chattool_25',['&lt;span class=&quot;tt&quot;&gt;ChatTool&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatTool&lt;/span&gt;)',['../index.html#autotoc_md53',1,'']]],
  ['msg_20chattoolcall_26',['&lt;span class=&quot;tt&quot;&gt;ChatToolCall&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatToolCall&lt;/span&gt;)',['../index.html#autotoc_md51',1,'']]],
  ['msg_20decisionanswer_27',['&lt;span class=&quot;tt&quot;&gt;DecisionAnswer&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/DecisionAnswer&lt;/span&gt;)',['../index.html#autotoc_md65',1,'']]],
  ['msg_20decisioninfo_28',['&lt;span class=&quot;tt&quot;&gt;DecisionInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/DecisionInfo&lt;/span&gt;)',['../index.html#autotoc_md63',1,'']]],
  ['msg_20decisionquestion_29',['&lt;span class=&quot;tt&quot;&gt;DecisionQuestion&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/DecisionQuestion&lt;/span&gt;)',['../index.html#autotoc_md64',1,'']]],
  ['msg_20generalinfo_30',['&lt;span class=&quot;tt&quot;&gt;GeneralInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/GeneralInfo&lt;/span&gt;)',['../index.html#autotoc_md56',1,'']]],
  ['msg_20grammartrigger_31',['&lt;span class=&quot;tt&quot;&gt;GrammarTrigger&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/GrammarTrigger&lt;/span&gt;)',['../index.html#autotoc_md48',1,'']]],
  ['msg_20logitbias_32',['&lt;span class=&quot;tt&quot;&gt;LogitBias&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LogitBias&lt;/span&gt;)',['../index.html#autotoc_md46',1,'']]],
  ['msg_20logitbiasarray_33',['&lt;span class=&quot;tt&quot;&gt;LogitBiasArray&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LogitBiasArray&lt;/span&gt;)',['../index.html#autotoc_md47',1,'']]],
  ['msg_20lora_34',['&lt;span class=&quot;tt&quot;&gt;LoRA&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LoRA&lt;/span&gt;)',['../index.html#autotoc_md80',1,'']]],
  ['msg_20metadata_35',['&lt;span class=&quot;tt&quot;&gt;Metadata&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/Metadata&lt;/span&gt;)',['../index.html#autotoc_md55',1,'']]],
  ['msg_20modelinfo_36',['&lt;span class=&quot;tt&quot;&gt;ModelInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ModelInfo&lt;/span&gt;)',['../index.html#autotoc_md57',1,'']]],
  ['msg_20partialresponse_37',['&lt;span class=&quot;tt&quot;&gt;PartialResponse&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/PartialResponse&lt;/span&gt;)',['../index.html#autotoc_md67',1,'']]],
  ['msg_20response_38',['&lt;span class=&quot;tt&quot;&gt;Response&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/Response&lt;/span&gt;)',['../index.html#autotoc_md66',1,'']]],
  ['msg_20ropeinfo_39',['&lt;span class=&quot;tt&quot;&gt;RoPEInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/RoPEInfo&lt;/span&gt;)',['../index.html#autotoc_md59',1,'']]],
  ['msg_20samplingconfig_40',['&lt;span class=&quot;tt&quot;&gt;SamplingConfig&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/SamplingConfig&lt;/span&gt;)',['../index.html#autotoc_md45',1,'']]],
  ['msg_20samplinginfo_41',['&lt;span class=&quot;tt&quot;&gt;SamplingInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/SamplingInfo&lt;/span&gt;)',['../index.html#autotoc_md62',1,'']]],
  ['msg_20tokenizerinfo_42',['&lt;span class=&quot;tt&quot;&gt;TokenizerInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/TokenizerInfo&lt;/span&gt;)',['../index.html#autotoc_md60',1,'']]],
  ['msg_20tokenprob_43',['&lt;span class=&quot;tt&quot;&gt;TokenProb&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/TokenProb&lt;/span&gt;)',['../index.html#autotoc_md68',1,'']]],
  ['msg_20tokenprobarray_44',['&lt;span class=&quot;tt&quot;&gt;TokenProbArray&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/TokenProbArray&lt;/span&gt;)',['../index.html#autotoc_md69',1,'']]],
  ['msg_20usagestats_45',['&lt;span class=&quot;tt&quot;&gt;UsageStats&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/UsageStats&lt;/span&gt;)',['../index.html#autotoc_md70',1,'']]],
  ['mtmd_20audio_20demo_46',['MTMD Audio Demo',['../index.html#autotoc_md128',1,'']]],
  ['mtp_20speculative_20decoding_20demo_47',['MTP Speculative Decoding Demo',['../index.html#autotoc_md117',1,'']]],
  ['multi_20audio_20demo_48',['Chat Multi-Audio Demo',['../index.html#autotoc_md130',1,'']]],
  ['multi_20image_20demo_49',['Chat Multi-Image Demo',['../index.html#autotoc_md126',1,'']]],
  ['multi_20image_20user_20input_20demo_50',['Chat Multi-Image (User Input) Demo',['../index.html#autotoc_md127',1,'']]],
  ['multimodal_51',['Multimodal (&lt;span class=&quot;tt&quot;&gt;multimodal.*&lt;/span&gt;)',['../index.html#autotoc_md25',1,'']]],
  ['multimodal_20embeddings_52',['Multimodal Embeddings',['../index.html#autotoc_md95',1,'']]],
  ['multimodal_20embeddings_20generation_20demo_53',['Multimodal Embeddings Generation Demo',['../index.html#autotoc_md119',1,'']]],
  ['multimodal_20multimodal_54',['Multimodal (&lt;span class=&quot;tt&quot;&gt;multimodal.*&lt;/span&gt;)',['../index.html#autotoc_md25',1,'']]],
  ['multimodal_20projector_20mmproj_55',['Multimodal Projector (&lt;span class=&quot;tt&quot;&gt;mmproj.*&lt;/span&gt;)',['../index.html#autotoc_md20',1,'']]]
];
