[project]
name = "llama_ros"
version = "6.0.12"
description = "ROS 2 packages to integrate llama.cpp into ROS 2"
requires-python = ">=3.10"
dependencies = [
    "langchain==1.4.2",
    "langchain-chroma==1.1.0",
    "langchain-community==0.4.2",
    "langchain-core==1.6.4",
    "langchain-text-splitters==1.1.2",
    "langgraph-prebuilt==1.1.0",
    "llama_ros_langchain",
]

[tool.uv]
package = false
override-dependencies = ["onnxruntime<1.21", "numpy<2"]

[tool.uv.workspace]
members = ["llama_ros_langchain"]

[tool.uv.sources]
llama_ros_langchain = { workspace = true }
