var searchData=
[
  ['label_5ftexts_0',['label_texts',['../structllama__ros_1_1DecisionModelConfig.html#a1db1f0e36b35d264afd6050929a8c3da',1,'llama_ros::DecisionModelConfig']]],
  ['labels_1',['labels',['../structllama__ros_1_1DecisionModelConfig.html#a06ef21fabefa9586b80cce17dfe0d17a',1,'llama_ros::DecisionModelConfig::labels'],['../structllama__ros_1_1DecisionTaskMeta.html#a0df41820e051f6e2da2d82835cf27c79',1,'llama_ros::DecisionTaskMeta::labels']]],
  ['langchain_2',['LangChain',['../index.html#autotoc_md91',1,'']]],
  ['languages_3',['languages',['../structllama__ros_1_1Metadata_1_1GeneralInfo.html#a0330d320289f1469a5b9317f1038656d',1,'llama_ros::Metadata::GeneralInfo']]],
  ['last_5fnl_5fpos_4',['last_nl_pos',['../classllama__ros_1_1ServerSlot.html#aeba7b6c91e09b027c2e64138c28d645f',1,'llama_ros::ServerSlot::last_nl_pos'],['../classServerSlot.html#aeba7b6c91e09b027c2e64138c28d645f',1,'ServerSlot::last_nl_pos']]],
  ['launch_5',['Launch',['../index.html#autotoc_md10',1,'llama_ros (Python Launch)'],['../index.html#autotoc_md14',1,'llava_ros (Python Launch)']]],
  ['launch_6',['launch',['../index.html#autotoc_md7',1,'']]],
  ['launch_20files_7',['Launch Files',['../index.html#autotoc_md9',1,'']]],
  ['launch_2epy_8',['launch.py',['../launch_8py.html',1,'']]],
  ['launch_5fllm_9',['launch_llm',['../namespacellama__cli_1_1api.html#a371fbc9ed6d622d0e40d514046b2151b',1,'llama_cli::api']]],
  ['launch_5fworker_5fthread_10',['launch_worker_thread',['../classllama__ros_1_1LlamaNode.html#ae8efc47a8aaf76a4e65ff9c91777e4d3',1,'llama_ros::LlamaNode']]],
  ['launchverb_11',['LaunchVerb',['../classllama__cli_1_1verb_1_1launch_1_1LaunchVerb.html',1,'llama_cli::verb::launch']]],
  ['layer_5fnorm_5fepsilon_12',['layer_norm_epsilon',['../structllama__ros_1_1Metadata_1_1AttentionInfo.html#af61203879a1e009f95326e9a9ae31672',1,'llama_ros::Metadata::AttentionInfo']]],
  ['layer_5fnorm_5frms_5fepsilon_13',['layer_norm_rms_epsilon',['../structllama__ros_1_1Metadata_1_1AttentionInfo.html#a353b3aa9db76b2d4634fbef63fc5d21a',1,'llama_ros::Metadata::AttentionInfo']]],
  ['license_14',['license',['../structllama__ros_1_1Metadata_1_1GeneralInfo.html#ae3324886507a533911ee90ace7921504',1,'llama_ros::Metadata::GeneralInfo::license'],['../namespacesetup.html#a8ed6f50a28bd6a8794f8e1153baa6de9',1,'setup.license']]],
  ['license_5flink_15',['license_link',['../structllama__ros_1_1Metadata_1_1GeneralInfo.html#a9542ca27e3c27faa3609b6dc88c91ca2',1,'llama_ros::Metadata::GeneralInfo']]],
  ['license_5fname_16',['license_name',['../structllama__ros_1_1Metadata_1_1GeneralInfo.html#a9be94c4cdc62936011fd96629c56d8f9',1,'llama_ros::Metadata::GeneralInfo']]],
  ['limit_5fbytes_5f_17',['limit_bytes_',['../classllama__ros_1_1PromptCache.html#a3437d17842e7a11b64ccd6cbb8d82750',1,'llama_ros::PromptCache::limit_bytes_'],['../classPromptCache.html#a3437d17842e7a11b64ccd6cbb8d82750',1,'PromptCache::limit_bytes_']]],
  ['limit_5ftokens_5f_18',['limit_tokens_',['../classllama__ros_1_1PromptCache.html#a08f63a020eb866d8b09ca1ab86b4cda3',1,'llama_ros::PromptCache::limit_tokens_'],['../classPromptCache.html#a08f63a020eb866d8b09ca1ab86b4cda3',1,'PromptCache::limit_tokens_']]],
  ['list_5floras_19',['list_loras',['../classllama__ros_1_1Llama.html#a6d9da64b80855bdf48229e2754cd263b',1,'llama_ros::Llama']]],
  ['list_5floras_5fservice_5f_20',['list_loras_service_',['../classllama__ros_1_1LlamaNode.html#ae48613d70306d3100ea7d332b0a5040c',1,'llama_ros::LlamaNode']]],
  ['list_5floras_5fservice_5fcallback_21',['list_loras_service_callback',['../classllama__ros_1_1LlamaNode.html#a5a79bd20864384f74c8d6faa9a8d2386',1,'llama_ros::LlamaNode']]],
  ['llama_22',['Llama',['../classllama__ros_1_1Llama.html',1,'llama_ros::Llama'],['../classllama__ros_1_1RequestHandler.html#a37a76a0165a609c33a210a297262b12e',1,'llama_ros::RequestHandler::Llama()'],['../classllama__ros_1_1Llama.html#afdea72b84f501d284f4d793a9fe5466c',1,'llama_ros::Llama::Llama()']]],
  ['llama_23',['llama',['../classllama__ros_1_1LlamaNode.html#add09929e4bb019eac008da2bdd4b8427',1,'llama_ros::LlamaNode::llama'],['../classLlamaDecisionTest.html#a28a549ee5d7dbab68852dc7eb930cd19',1,'LlamaDecisionTest::llama'],['../classLlamaOpenJevTest.html#ac6533ff11a89ab1b2108c7a3c8fbb43b',1,'LlamaOpenJevTest::llama'],['../classLlamaEnvDecisionTest.html#a80ad998adba755c2bba5194eef89c7e7',1,'LlamaEnvDecisionTest::llama'],['../classLlamaDeploymentTest.html#af388e7fec6777b219fafc53044cbdb4a',1,'LlamaDeploymentTest::llama'],['../classLlamaEmbeddingsTest.html#a3146899722c94d6e0bd912db0a23f5db',1,'LlamaEmbeddingsTest::llama'],['../classLlamaGenerationTest.html#a288e3345aa9c1f3ec3aa486b7f988f0a',1,'LlamaGenerationTest::llama'],['../classLlamaLoRATest.html#a328a006ff490454b99f3821dd19eef8e',1,'LlamaLoRATest::llama'],['../classLlamaRerankingTest.html#ae8eba3dc20d50e8de8c7c8bf0270b4a7',1,'LlamaRerankingTest::llama']]],
  ['llama_2d3_2dspeculative_24',['llama-3-speculative',['../namespacellama-3-speculative.html',1,'']]],
  ['llama_2d3_2dspeculative_2elaunch_2epy_25',['llama-3-speculative.launch.py',['../llama-3-speculative_8launch_8py.html',1,'']]],
  ['llama_2ecpp_26',['llama.cpp',['../llama_8cpp.html',1,'']]],
  ['llama_2ehpp_27',['llama.hpp',['../llama_8hpp.html',1,'']]],
  ['llama_2epy_28',['llama.py',['../llama_8py.html',1,'']]],
  ['llama_5f_29',['llama_',['../classllama__ros_1_1RequestHandler.html#a785fc0eef823588ba02358651f3b74d9',1,'llama_ros::RequestHandler']]],
  ['llama_5fbt_30',['llama_bt',['../namespacellama__bt.html',1,'']]],
  ['llama_5fcli_31',['llama_cli',['../namespacellama__cli.html',1,'llama_cli'],['../index.html#autotoc_md6',1,'llama_cli']]],
  ['llama_5fcli_3a_3aapi_32',['api',['../namespacellama__cli_1_1api.html',1,'llama_cli']]],
  ['llama_5fcli_3a_3acommand_33',['command',['../namespacellama__cli_1_1command.html',1,'llama_cli']]],
  ['llama_5fcli_3a_3acommand_3a_3allama_34',['llama',['../namespacellama__cli_1_1command_1_1llama.html',1,'llama_cli::command']]],
  ['llama_5fcli_3a_3averb_35',['verb',['../namespacellama__cli_1_1verb.html',1,'llama_cli']]],
  ['llama_5fcli_3a_3averb_3a_3alaunch_36',['launch',['../namespacellama__cli_1_1verb_1_1launch.html',1,'llama_cli::verb']]],
  ['llama_5fcli_3a_3averb_3a_3aprompt_37',['prompt',['../namespacellama__cli_1_1verb_1_1prompt.html',1,'llama_cli::verb']]],
  ['llama_5fclient_5fnode_2epy_38',['llama_client_node.py',['../llama__client__node_8py.html',1,'']]],
  ['llama_5fdemo_5fnode_2epy_39',['llama_demo_node.py',['../llama__demo__node_8py.html',1,'']]],
  ['llama_5fdemos_40',['llama_demos',['../namespacellama__demos.html',1,'']]],
  ['llama_5fdemos_3a_3achatllama_5fagent_5fdemo_5fnode_41',['chatllama_agent_demo_node',['../namespacellama__demos_1_1chatllama__agent__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3achatllama_5faudio_5fdemo_5fnode_42',['chatllama_audio_demo_node',['../namespacellama__demos_1_1chatllama__audio__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3achatllama_5fdemo_5fnode_43',['chatllama_demo_node',['../namespacellama__demos_1_1chatllama__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3achatllama_5fimage_5fdemo_5fnode_44',['chatllama_image_demo_node',['../namespacellama__demos_1_1chatllama__image__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3achatllama_5fmulti_5faudio_5fdemo_5fnode_45',['chatllama_multi_audio_demo_node',['../namespacellama__demos_1_1chatllama__multi__audio__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3achatllama_5fmulti_5fimage_5fdemo_5fnode_46',['chatllama_multi_image_demo_node',['../namespacellama__demos_1_1chatllama__multi__image__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3achatllama_5fmulti_5fimage_5fuser_5fdemo_5fnode_47',['chatllama_multi_image_user_demo_node',['../namespacellama__demos_1_1chatllama__multi__image__user__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3achatllama_5fpddl_5fdemo_5fnode_48',['chatllama_pddl_demo_node',['../namespacellama__demos_1_1chatllama__pddl__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3achatllama_5freasoning_5fdemo_5fnode_49',['chatllama_reasoning_demo_node',['../namespacellama__demos_1_1chatllama__reasoning__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3achatllama_5freasoning_5ftools_5fdemo_5fnode_50',['chatllama_reasoning_tools_demo_node',['../namespacellama__demos_1_1chatllama__reasoning__tools__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3achatllama_5fstreaming_5ftools_5fdemo_5fnode_51',['chatllama_streaming_tools_demo_node',['../namespacellama__demos_1_1chatllama__streaming__tools__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3achatllama_5fstructured_5fdemo_5fnode_52',['chatllama_structured_demo_node',['../namespacellama__demos_1_1chatllama__structured__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3achatllama_5ftools_5fdemo_5fnode_53',['chatllama_tools_demo_node',['../namespacellama__demos_1_1chatllama__tools__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3adecision_5fdemo_5fnode_54',['decision_demo_node',['../namespacellama__demos_1_1decision__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3aimage_5fdecision_5fdemo_5fnode_55',['image_decision_demo_node',['../namespacellama__demos_1_1image__decision__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3allama_5fdemo_5fnode_56',['llama_demo_node',['../namespacellama__demos_1_1llama__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3allama_5fembeddings_5fdemo_5fnode_57',['llama_embeddings_demo_node',['../namespacellama__demos_1_1llama__embeddings__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3allama_5frag_5fdemo_5fnode_58',['llama_rag_demo_node',['../namespacellama__demos_1_1llama__rag__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3allama_5frerank_5fdemo_5fnode_59',['llama_rerank_demo_node',['../namespacellama__demos_1_1llama__rerank__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3allama_5fslots_5fdemo_5fnode_60',['llama_slots_demo_node',['../namespacellama__demos_1_1llama__slots__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3allava_5fdemo_5fnode_61',['llava_demo_node',['../namespacellama__demos_1_1llava__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3amtmd_5faudio_5fdemo_5fnode_62',['mtmd_audio_demo_node',['../namespacellama__demos_1_1mtmd__audio__demo__node.html',1,'llama_demos']]],
  ['llama_5fembeddings_5fdemo_5fnode_2epy_63',['llama_embeddings_demo_node.py',['../llama__embeddings__demo__node_8py.html',1,'']]],
  ['llama_5finit_64',['llama_init',['../classllama__ros_1_1Llama.html#a7b54f9a0537fd0544fb0401f7c19fe5d',1,'llama_ros::Llama']]],
  ['llama_5flog_5fdebug_65',['LLAMA_LOG_DEBUG',['../logs_8hpp.html#aa13075de37f6ec373e764a61ccbf92c7',1,'logs.hpp']]],
  ['llama_5flog_5ferror_66',['LLAMA_LOG_ERROR',['../logs_8hpp.html#af57cb87dacb596fda45658e510d9ac53',1,'logs.hpp']]],
  ['llama_5flog_5finfo_67',['LLAMA_LOG_INFO',['../logs_8hpp.html#a59f368b6a6adf649e06afe07ef10508b',1,'logs.hpp']]],
  ['llama_5flog_5fwarn_68',['LLAMA_LOG_WARN',['../logs_8hpp.html#a7903d2c72fa8e8887bad72cb85d27e8c',1,'logs.hpp']]],
  ['llama_5fmain_2ecpp_69',['llama_main.cpp',['../llama__main_8cpp.html',1,'']]],
  ['llama_5fmsgs_20action_20generatechatcompletions_70',['llama_msgs action GenerateChatCompletions',['../index.html#autotoc_md74',1,'&lt;span class=&quot;tt&quot;&gt;GenerateChatCompletions&lt;/span&gt; Feedback (&lt;span class=&quot;tt&quot;&gt;llama_msgs/action/GenerateChatCompletions&lt;/span&gt;)'],['../index.html#autotoc_md71',1,'&lt;span class=&quot;tt&quot;&gt;GenerateChatCompletions&lt;/span&gt; Goal (&lt;span class=&quot;tt&quot;&gt;llama_msgs/action/GenerateChatCompletions&lt;/span&gt;)'],['../index.html#autotoc_md72',1,'&lt;span class=&quot;tt&quot;&gt;GenerateChatCompletions&lt;/span&gt; Result (&lt;span class=&quot;tt&quot;&gt;llama_msgs/action/GenerateChatCompletions&lt;/span&gt;)']]],
  ['llama_5fmsgs_20action_20generateresponse_71',['llama_msgs action GenerateResponse',['../index.html#autotoc_md79',1,'&lt;span class=&quot;tt&quot;&gt;GenerateResponse&lt;/span&gt; Feedback (&lt;span class=&quot;tt&quot;&gt;llama_msgs/action/GenerateResponse&lt;/span&gt;)'],['../index.html#autotoc_md77',1,'&lt;span class=&quot;tt&quot;&gt;GenerateResponse&lt;/span&gt; Goal (&lt;span class=&quot;tt&quot;&gt;llama_msgs/action/GenerateResponse&lt;/span&gt;)'],['../index.html#autotoc_md78',1,'&lt;span class=&quot;tt&quot;&gt;GenerateResponse&lt;/span&gt; Result (&lt;span class=&quot;tt&quot;&gt;llama_msgs/action/GenerateResponse&lt;/span&gt;)']]],
  ['llama_5fmsgs_20msg_20attentioninfo_72',['&lt;span class=&quot;tt&quot;&gt;AttentionInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/AttentionInfo&lt;/span&gt;)',['../index.html#autotoc_md58',1,'']]],
  ['llama_5fmsgs_20msg_20basemodelinfo_73',['&lt;span class=&quot;tt&quot;&gt;BaseModelInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/BaseModelInfo&lt;/span&gt;)',['../index.html#autotoc_md61',1,'']]],
  ['llama_5fmsgs_20msg_20chatchoice_74',['&lt;span class=&quot;tt&quot;&gt;ChatChoice&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatChoice&lt;/span&gt;)',['../index.html#autotoc_md73',1,'']]],
  ['llama_5fmsgs_20msg_20chatchoicechunk_75',['&lt;span class=&quot;tt&quot;&gt;ChatChoiceChunk&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatChoiceChunk&lt;/span&gt;)',['../index.html#autotoc_md75',1,'']]],
  ['llama_5fmsgs_20msg_20chatcontent_76',['&lt;span class=&quot;tt&quot;&gt;ChatContent&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatContent&lt;/span&gt;)',['../index.html#autotoc_md50',1,'']]],
  ['llama_5fmsgs_20msg_20chatdeltachunk_77',['&lt;span class=&quot;tt&quot;&gt;ChatDeltaChunk&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatDeltaChunk&lt;/span&gt;)',['../index.html#autotoc_md76',1,'']]],
  ['llama_5fmsgs_20msg_20chatmessage_78',['&lt;span class=&quot;tt&quot;&gt;ChatMessage&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatMessage&lt;/span&gt;)',['../index.html#autotoc_md49',1,'']]],
  ['llama_5fmsgs_20msg_20chatreasoningformat_79',['&lt;span class=&quot;tt&quot;&gt;ChatReasoningFormat&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatReasoningFormat&lt;/span&gt;)',['../index.html#autotoc_md54',1,'']]],
  ['llama_5fmsgs_20msg_20chatreqtool_80',['&lt;span class=&quot;tt&quot;&gt;ChatReqTool&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatReqTool&lt;/span&gt;)',['../index.html#autotoc_md52',1,'']]],
  ['llama_5fmsgs_20msg_20chattool_81',['&lt;span class=&quot;tt&quot;&gt;ChatTool&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatTool&lt;/span&gt;)',['../index.html#autotoc_md53',1,'']]],
  ['llama_5fmsgs_20msg_20chattoolcall_82',['&lt;span class=&quot;tt&quot;&gt;ChatToolCall&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatToolCall&lt;/span&gt;)',['../index.html#autotoc_md51',1,'']]],
  ['llama_5fmsgs_20msg_20decisionanswer_83',['&lt;span class=&quot;tt&quot;&gt;DecisionAnswer&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/DecisionAnswer&lt;/span&gt;)',['../index.html#autotoc_md65',1,'']]],
  ['llama_5fmsgs_20msg_20decisioninfo_84',['&lt;span class=&quot;tt&quot;&gt;DecisionInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/DecisionInfo&lt;/span&gt;)',['../index.html#autotoc_md63',1,'']]],
  ['llama_5fmsgs_20msg_20decisionquestion_85',['&lt;span class=&quot;tt&quot;&gt;DecisionQuestion&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/DecisionQuestion&lt;/span&gt;)',['../index.html#autotoc_md64',1,'']]],
  ['llama_5fmsgs_20msg_20generalinfo_86',['&lt;span class=&quot;tt&quot;&gt;GeneralInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/GeneralInfo&lt;/span&gt;)',['../index.html#autotoc_md56',1,'']]],
  ['llama_5fmsgs_20msg_20grammartrigger_87',['&lt;span class=&quot;tt&quot;&gt;GrammarTrigger&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/GrammarTrigger&lt;/span&gt;)',['../index.html#autotoc_md48',1,'']]],
  ['llama_5fmsgs_20msg_20logitbias_88',['&lt;span class=&quot;tt&quot;&gt;LogitBias&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LogitBias&lt;/span&gt;)',['../index.html#autotoc_md46',1,'']]],
  ['llama_5fmsgs_20msg_20logitbiasarray_89',['&lt;span class=&quot;tt&quot;&gt;LogitBiasArray&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LogitBiasArray&lt;/span&gt;)',['../index.html#autotoc_md47',1,'']]],
  ['llama_5fmsgs_20msg_20lora_90',['&lt;span class=&quot;tt&quot;&gt;LoRA&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LoRA&lt;/span&gt;)',['../index.html#autotoc_md80',1,'']]],
  ['llama_5fmsgs_20msg_20metadata_91',['&lt;span class=&quot;tt&quot;&gt;Metadata&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/Metadata&lt;/span&gt;)',['../index.html#autotoc_md55',1,'']]],
  ['llama_5fmsgs_20msg_20modelinfo_92',['&lt;span class=&quot;tt&quot;&gt;ModelInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ModelInfo&lt;/span&gt;)',['../index.html#autotoc_md57',1,'']]],
  ['llama_5fmsgs_20msg_20partialresponse_93',['&lt;span class=&quot;tt&quot;&gt;PartialResponse&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/PartialResponse&lt;/span&gt;)',['../index.html#autotoc_md67',1,'']]],
  ['llama_5fmsgs_20msg_20response_94',['&lt;span class=&quot;tt&quot;&gt;Response&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/Response&lt;/span&gt;)',['../index.html#autotoc_md66',1,'']]],
  ['llama_5fmsgs_20msg_20ropeinfo_95',['&lt;span class=&quot;tt&quot;&gt;RoPEInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/RoPEInfo&lt;/span&gt;)',['../index.html#autotoc_md59',1,'']]],
  ['llama_5fmsgs_20msg_20samplingconfig_96',['&lt;span class=&quot;tt&quot;&gt;SamplingConfig&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/SamplingConfig&lt;/span&gt;)',['../index.html#autotoc_md45',1,'']]],
  ['llama_5fmsgs_20msg_20samplinginfo_97',['&lt;span class=&quot;tt&quot;&gt;SamplingInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/SamplingInfo&lt;/span&gt;)',['../index.html#autotoc_md62',1,'']]],
  ['llama_5fmsgs_20msg_20tokenizerinfo_98',['&lt;span class=&quot;tt&quot;&gt;TokenizerInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/TokenizerInfo&lt;/span&gt;)',['../index.html#autotoc_md60',1,'']]],
  ['llama_5fmsgs_20msg_20tokenprob_99',['&lt;span class=&quot;tt&quot;&gt;TokenProb&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/TokenProb&lt;/span&gt;)',['../index.html#autotoc_md68',1,'']]],
  ['llama_5fmsgs_20msg_20tokenprobarray_100',['&lt;span class=&quot;tt&quot;&gt;TokenProbArray&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/TokenProbArray&lt;/span&gt;)',['../index.html#autotoc_md69',1,'']]],
  ['llama_5fmsgs_20msg_20usagestats_101',['&lt;span class=&quot;tt&quot;&gt;UsageStats&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/UsageStats&lt;/span&gt;)',['../index.html#autotoc_md70',1,'']]],
  ['llama_5fnode_2ecpp_102',['llama_node.cpp',['../llama__node_8cpp.html',1,'']]],
  ['llama_5fnode_2ehpp_103',['llama_node.hpp',['../llama__node_8hpp.html',1,'']]],
  ['llama_5fparams_2ecpp_104',['llama_params.cpp',['../llama__params_8cpp.html',1,'']]],
  ['llama_5fparams_2ehpp_105',['llama_params.hpp',['../llama__params_8hpp.html',1,'']]],
  ['llama_5frag_5fdemo_5fnode_2epy_106',['llama_rag_demo_node.py',['../llama__rag__demo__node_8py.html',1,'']]],
  ['llama_5frerank_5fdemo_5fnode_2epy_107',['llama_rerank_demo_node.py',['../llama__rerank__demo__node_8py.html',1,'']]],
  ['llama_5fros_108',['llama_ros',['../namespacellama__ros.html',1,'llama_ros'],['../index.html',1,'llama_ros']]],
  ['llama_5fros_20chain_109',['llama_ros (Chain)',['../index.html#autotoc_md92',1,'']]],
  ['llama_5fros_20llm_20rag_20reranker_110',['llama_ros (LLM + RAG + Reranker)',['../index.html#autotoc_md97',1,'']]],
  ['llama_5fros_20python_20launch_111',['llama_ros (Python Launch)',['../index.html#autotoc_md10',1,'']]],
  ['llama_5fros_20reranker_112',['llama_ros (Reranker)',['../index.html#autotoc_md96',1,'']]],
  ['llama_5fros_20speculative_20decoding_113',['llama_ros (Speculative Decoding)',['../index.html#autotoc_md13',1,'']]],
  ['llama_5fros_20stream_114',['llama_ros (Stream)',['../index.html#autotoc_md93',1,'']]],
  ['llama_5fros_20yaml_20config_115',['llama_ros (YAML Config)',['../index.html#autotoc_md11',1,'']]],
  ['llama_5fros_20yaml_20config_20model_20shards_116',['llama_ros (YAML Config + model shards)',['../index.html#autotoc_md12',1,'']]],
  ['llama_5fros_3a_3allama_5fclient_5fnode_117',['llama_client_node',['../namespacellama__ros_1_1llama__client__node.html',1,'llama_ros']]],
  ['llama_5fros_5fembeddings_20rag_118',['llama_ros_embeddings (RAG)',['../index.html#autotoc_md95',1,'']]],
  ['llama_5fslots_5fdemo_5fnode_2epy_119',['llama_slots_demo_node.py',['../llama__slots__demo__node_8py.html',1,'']]],
  ['llama_5futils_120',['llama_utils',['../namespacellama__utils.html',1,'']]],
  ['llamaclientnode_121',['LlamaClientNode',['../classllama__ros_1_1llama__client__node_1_1LlamaClientNode.html',1,'llama_ros::llama_client_node']]],
  ['llamacommand_122',['LlamaCommand',['../classllama__cli_1_1command_1_1llama_1_1LlamaCommand.html',1,'llama_cli::command::llama']]],
  ['llamadecisiontest_123',['LlamaDecisionTest',['../classLlamaDecisionTest.html',1,'']]],
  ['llamadeploymenttest_124',['LlamaDeploymentTest',['../classLlamaDeploymentTest.html',1,'']]],
  ['llamaembeddingstest_125',['LlamaEmbeddingsTest',['../classLlamaEmbeddingsTest.html',1,'']]],
  ['llamaenvdecisiontest_126',['LlamaEnvDecisionTest',['../classLlamaEnvDecisionTest.html',1,'']]],
  ['llamagenerationtest_127',['LlamaGenerationTest',['../classLlamaGenerationTest.html',1,'']]],
  ['llamaloratest_128',['LlamaLoRATest',['../classLlamaLoRATest.html',1,'']]],
  ['llamanode_129',['LlamaNode',['../classllama__ros_1_1LlamaNode.html',1,'llama_ros::LlamaNode'],['../classllama__ros_1_1LlamaNode.html#adc90c82214422e4d5c11bfc480e5ff93',1,'llama_ros::LlamaNode::LlamaNode()']]],
  ['llamaopenjevtest_130',['LlamaOpenJevTest',['../classLlamaOpenJevTest.html',1,'']]],
  ['llamaparams_131',['LlamaParams',['../structllama__utils_1_1LlamaParams.html',1,'llama_utils']]],
  ['llamaparamstest_132',['LlamaParamsTest',['../classLlamaParamsTest.html',1,'']]],
  ['llamarerankingtest_133',['LlamaRerankingTest',['../classLlamaRerankingTest.html',1,'']]],
  ['llava_134',['Llava',['../classllava__ros_1_1Llava.html',1,'llava_ros::Llava'],['../classllava__ros_1_1Llava.html#afd9dfc6ff1fa7194fe92a47bb0ad9d01',1,'llava_ros::Llava::Llava()']]],
  ['llava_135',['llava',['../index.html#autotoc_md87',1,'Generate Response (llava)'],['../classLlavaDecisionTest.html#a777e2c46ca004155d8b133ab43d133e7',1,'LlavaDecisionTest::llava'],['../classLlavaClefDecisionTest.html#aafbde3825777c635413676b90b4872a9',1,'LlavaClefDecisionTest::llava']]],
  ['llava_2ecpp_136',['llava.cpp',['../llava_8cpp.html',1,'']]],
  ['llava_2ehpp_137',['llava.hpp',['../llava_8hpp.html',1,'']]],
  ['llava_5f_138',['llava_',['../classllava__ros_1_1LlavaCompletionRequestHandler.html#a02534c93c9437443038d0cf0062513b5',1,'llava_ros::LlavaCompletionRequestHandler::llava_'],['../classllava__ros_1_1LlavaChatCompletionRequestHandler.html#a4e0b293b031cae5fb5370e2249772ca1',1,'llava_ros::LlavaChatCompletionRequestHandler::llava_']]],
  ['llava_5fchat_5fcompletion_5fhandler_5f_139',['llava_chat_completion_handler_',['../classllava__ros_1_1Llava.html#a51b971acc306dff5d249b135fd5a6273',1,'llava_ros::Llava']]],
  ['llava_5fcompletion_5fhandler_5f_140',['llava_completion_handler_',['../classllava__ros_1_1Llava.html#ade09d310118dd207b9819e9486a9db1f',1,'llava_ros::Llava']]],
  ['llava_5fdemo_5fnode_2epy_141',['llava_demo_node.py',['../llava__demo__node_8py.html',1,'']]],
  ['llava_5fmain_2ecpp_142',['llava_main.cpp',['../llava__main_8cpp.html',1,'']]],
  ['llava_5fnode_2ecpp_143',['llava_node.cpp',['../llava__node_8cpp.html',1,'']]],
  ['llava_5fnode_2ehpp_144',['llava_node.hpp',['../llava__node_8hpp.html',1,'']]],
  ['llava_5frequest_5fhandler_2ecpp_145',['llava_request_handler.cpp',['../llava__request__handler_8cpp.html',1,'']]],
  ['llava_5frequest_5fhandler_2ehpp_146',['llava_request_handler.hpp',['../llava__request__handler_8hpp.html',1,'']]],
  ['llava_5fros_147',['llava_ros',['../namespacellava__ros.html',1,'llava_ros'],['../index.html#autotoc_md94',1,'llava_ros']]],
  ['llava_5fros_20audio_148',['llava_ros (Audio)',['../index.html#autotoc_md16',1,'']]],
  ['llava_5fros_20python_20launch_149',['llava_ros (Python Launch)',['../index.html#autotoc_md14',1,'']]],
  ['llava_5fros_20yaml_20config_150',['llava_ros (YAML Config)',['../index.html#autotoc_md15',1,'']]],
  ['llavachatcompletionrequesthandler_151',['LlavaChatCompletionRequestHandler',['../classllava__ros_1_1LlavaChatCompletionRequestHandler.html',1,'llava_ros::LlavaChatCompletionRequestHandler'],['../classllava__ros_1_1Llava.html#a241fed29ed745f8da38227fba492c9e7',1,'llava_ros::Llava::LlavaChatCompletionRequestHandler()'],['../classllava__ros_1_1LlavaChatCompletionRequestHandler.html#a2df1aeb1d1ff8f8f88737d62fb2908d1',1,'llava_ros::LlavaChatCompletionRequestHandler::LlavaChatCompletionRequestHandler()']]],
  ['llavaclefdecisiontest_152',['LlavaClefDecisionTest',['../classLlavaClefDecisionTest.html',1,'']]],
  ['llavacompletionrequesthandler_153',['LlavaCompletionRequestHandler',['../classllava__ros_1_1LlavaCompletionRequestHandler.html',1,'llava_ros::LlavaCompletionRequestHandler'],['../classllava__ros_1_1Llava.html#a2a9d71be8f6375a40de13a24e28aa720',1,'llava_ros::Llava::LlavaCompletionRequestHandler()'],['../classllava__ros_1_1LlavaCompletionRequestHandler.html#a1dc2be22e5ac06df594374317df83196',1,'llava_ros::LlavaCompletionRequestHandler::LlavaCompletionRequestHandler()']]],
  ['llavadecisiontest_154',['LlavaDecisionTest',['../classLlavaDecisionTest.html',1,'']]],
  ['llavanode_155',['LlavaNode',['../classllava__ros_1_1LlavaNode.html',1,'llava_ros::LlavaNode'],['../classllava__ros_1_1LlavaNode.html#aeeaefad9b9adeebe6d58e668693f21e4',1,'llava_ros::LlavaNode::LlavaNode()']]],
  ['llm_20chat_20template_20rag_20reranking_20stream_156',['RAG Demo (LLM + chat template + RAG + Reranking + Stream)',['../index.html#autotoc_md112',1,'']]],
  ['llm_20demo_157',['LLM Demo',['../index.html#autotoc_md105',1,'']]],
  ['llm_20rag_20reranker_158',['llama_ros (LLM + RAG + Reranker)',['../index.html#autotoc_md97',1,'']]],
  ['load_5faudios_159',['load_audios',['../classllava__ros_1_1LlavaNode.html#affaa939213cf52e83179dfae5fd9fbd9',1,'llava_ros::LlavaNode']]],
  ['load_5fdecision_5fimages_160',['load_decision_images',['../classllama__ros_1_1LlamaNode.html#adfe887c13e2a0dc47b9119a223496215',1,'llama_ros::LlamaNode::load_decision_images()'],['../classllava__ros_1_1LlavaNode.html#a6232c7138be03ea668c6358e98f76d49',1,'llava_ros::LlavaNode::load_decision_images()']]],
  ['load_5fimage_5ffrom_5furl_161',['load_image_from_url',['../namespacellama__demos_1_1image__decision__demo__node.html#a4da3090223c689d4b337d0b20c061b9f',1,'llama_demos.image_decision_demo_node.load_image_from_url()'],['../namespacellama__demos_1_1llava__demo__node.html#a4da3090223c689d4b337d0b20c061b9f',1,'llama_demos.llava_demo_node.load_image_from_url()']]],
  ['load_5fimages_162',['load_images',['../classllava__ros_1_1LlavaNode.html#a45e7dec9c8b63d0515c55c24ce1c8ce1',1,'llava_ros::LlavaNode']]],
  ['load_5fmodule_163',['load_module',['../namespacetest_1_1test__prompt__cancellation.html#a36c34cddb1c628e703f68b65128c6ed5',1,'test::test_prompt_cancellation']]],
  ['load_5fmtmd_164',['load_mtmd',['../classllava__ros_1_1Llava.html#a71783572ece719326f645604be97284f',1,'llava_ros::Llava']]],
  ['load_5fmtmds_165',['load_mtmds',['../classllava__ros_1_1Llava.html#a0bbd8833d4426d8bb7db0ffc14df3ecf',1,'llava_ros::Llava']]],
  ['log_5fdebug_166',['log_debug',['../namespacellama__utils.html#a51d7de618ac0a94f819d3369f23e7115',1,'llama_utils']]],
  ['log_5ferror_167',['log_error',['../namespacellama__utils.html#ad078a11b643e3437eeaeed4a0b838cc3',1,'llama_utils']]],
  ['log_5finfo_168',['log_info',['../namespacellama__utils.html#ad5ed9b1eb69b5917bb6ada478b5a1ea5',1,'llama_utils']]],
  ['log_5flevel_169',['log_level',['../namespacellama__utils.html#aac7a26212d9753c66d862d08e746832f',1,'llama_utils']]],
  ['log_5fwarn_170',['log_warn',['../namespacellama__utils.html#a4c0091de6f42ee4173d1abaa18b8a89d',1,'llama_utils']]],
  ['logfunction_171',['LogFunction',['../namespacellama__utils.html#a9b29ce3d5c13af766ffd9aac9c51d617',1,'llama_utils']]],
  ['logit_172',['logit',['../namespacellama__utils.html#ad789d8dfa8e54aedb238027ee7c74e6d',1,'llama_utils']]],
  ['logitbias_173',['&lt;span class=&quot;tt&quot;&gt;LogitBias&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LogitBias&lt;/span&gt;)',['../index.html#autotoc_md46',1,'']]],
  ['logitbias_20llama_5fmsgs_20msg_20logitbias_174',['&lt;span class=&quot;tt&quot;&gt;LogitBias&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LogitBias&lt;/span&gt;)',['../index.html#autotoc_md46',1,'']]],
  ['logitbiasarray_175',['&lt;span class=&quot;tt&quot;&gt;LogitBiasArray&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LogitBiasArray&lt;/span&gt;)',['../index.html#autotoc_md47',1,'']]],
  ['logitbiasarray_20llama_5fmsgs_20msg_20logitbiasarray_176',['&lt;span class=&quot;tt&quot;&gt;LogitBiasArray&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LogitBiasArray&lt;/span&gt;)',['../index.html#autotoc_md47',1,'']]],
  ['loglevel_177',['LogLevel',['../namespacellama__utils.html#a386024dced31ce4ae6a2bb5e0b97fefd',1,'llama_utils']]],
  ['logprob_178',['LogProb',['../structllama__ros_1_1LogProb.html',1,'llama_ros']]],
  ['logs_2ecpp_179',['logs.cpp',['../logs_8cpp.html',1,'']]],
  ['logs_2ehpp_180',['logs.hpp',['../logs_8hpp.html',1,'']]],
  ['long_5fprompt_181',['long_prompt',['../classPrecomputeCancelTest.html#a25f0abee5cb20793c7fcd41f17761478',1,'PrecomputeCancelTest']]],
  ['lora_182',['LoRA',['../index.html#autotoc_md80',1,'&lt;span class=&quot;tt&quot;&gt;LoRA&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LoRA&lt;/span&gt;)'],['../structllama__ros_1_1LoRA.html',1,'llama_ros::LoRA']]],
  ['lora_183',['lora',['../structllama__ros_1_1ServerSlot_1_1slot__params.html#a06375c56a57ddc305a52eb84f1857055',1,'llama_ros::ServerSlot::slot_params::lora'],['../structServerSlot_1_1slot__params.html#a06375c56a57ddc305a52eb84f1857055',1,'ServerSlot::slot_params::lora'],['../index.html#autotoc_md43',1,'LoRA Adapters (&lt;span class=&quot;tt&quot;&gt;lora.*&lt;/span&gt;)']]],
  ['lora_20adapters_184',['LoRA Adapters',['../index.html#autotoc_md81',1,'']]],
  ['lora_20adapters_20lora_185',['LoRA Adapters (&lt;span class=&quot;tt&quot;&gt;lora.*&lt;/span&gt;)',['../index.html#autotoc_md43',1,'']]],
  ['lora_20llama_5fmsgs_20msg_20lora_186',['&lt;span class=&quot;tt&quot;&gt;LoRA&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LoRA&lt;/span&gt;)',['../index.html#autotoc_md80',1,'']]],
  ['lora_5fadapters_187',['lora_adapters',['../classllama__ros_1_1Llama.html#a3343eadcff7fe39bf6254f616ac96908',1,'llama_ros::Llama::lora_adapters'],['../classllama__ros_1_1ServerSlot.html#a9833f563922b3aebbbfb218a15f39af6',1,'llama_ros::ServerSlot::lora_adapters'],['../classServerSlot.html#a9833f563922b3aebbbfb218a15f39af6',1,'ServerSlot::lora_adapters']]],
  ['lora_5fpath_188',['lora_path',['../classLlamaLoRATest.html#aca471fca84e09c2c763f01bc8de1e861',1,'LlamaLoRATest']]]
];
