var searchData=
[
  ['langchain_0',['LangChain',['../index.html#autotoc_md91',1,'']]],
  ['launch_1',['Launch',['../index.html#autotoc_md10',1,'llama_ros (Python Launch)'],['../index.html#autotoc_md14',1,'llava_ros (Python Launch)']]],
  ['launch_2',['launch',['../index.html#autotoc_md7',1,'']]],
  ['launch_20files_3',['Launch Files',['../index.html#autotoc_md9',1,'']]],
  ['llama_5fcli_4',['llama_cli',['../index.html#autotoc_md6',1,'']]],
  ['llama_5fmsgs_20action_20generatechatcompletions_5',['llama_msgs action GenerateChatCompletions',['../index.html#autotoc_md74',1,'&lt;span class=&quot;tt&quot;&gt;GenerateChatCompletions&lt;/span&gt; Feedback (&lt;span class=&quot;tt&quot;&gt;llama_msgs/action/GenerateChatCompletions&lt;/span&gt;)'],['../index.html#autotoc_md71',1,'&lt;span class=&quot;tt&quot;&gt;GenerateChatCompletions&lt;/span&gt; Goal (&lt;span class=&quot;tt&quot;&gt;llama_msgs/action/GenerateChatCompletions&lt;/span&gt;)'],['../index.html#autotoc_md72',1,'&lt;span class=&quot;tt&quot;&gt;GenerateChatCompletions&lt;/span&gt; Result (&lt;span class=&quot;tt&quot;&gt;llama_msgs/action/GenerateChatCompletions&lt;/span&gt;)']]],
  ['llama_5fmsgs_20action_20generateresponse_6',['llama_msgs action GenerateResponse',['../index.html#autotoc_md79',1,'&lt;span class=&quot;tt&quot;&gt;GenerateResponse&lt;/span&gt; Feedback (&lt;span class=&quot;tt&quot;&gt;llama_msgs/action/GenerateResponse&lt;/span&gt;)'],['../index.html#autotoc_md77',1,'&lt;span class=&quot;tt&quot;&gt;GenerateResponse&lt;/span&gt; Goal (&lt;span class=&quot;tt&quot;&gt;llama_msgs/action/GenerateResponse&lt;/span&gt;)'],['../index.html#autotoc_md78',1,'&lt;span class=&quot;tt&quot;&gt;GenerateResponse&lt;/span&gt; Result (&lt;span class=&quot;tt&quot;&gt;llama_msgs/action/GenerateResponse&lt;/span&gt;)']]],
  ['llama_5fmsgs_20msg_20attentioninfo_7',['&lt;span class=&quot;tt&quot;&gt;AttentionInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/AttentionInfo&lt;/span&gt;)',['../index.html#autotoc_md58',1,'']]],
  ['llama_5fmsgs_20msg_20basemodelinfo_8',['&lt;span class=&quot;tt&quot;&gt;BaseModelInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/BaseModelInfo&lt;/span&gt;)',['../index.html#autotoc_md61',1,'']]],
  ['llama_5fmsgs_20msg_20chatchoice_9',['&lt;span class=&quot;tt&quot;&gt;ChatChoice&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatChoice&lt;/span&gt;)',['../index.html#autotoc_md73',1,'']]],
  ['llama_5fmsgs_20msg_20chatchoicechunk_10',['&lt;span class=&quot;tt&quot;&gt;ChatChoiceChunk&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatChoiceChunk&lt;/span&gt;)',['../index.html#autotoc_md75',1,'']]],
  ['llama_5fmsgs_20msg_20chatcontent_11',['&lt;span class=&quot;tt&quot;&gt;ChatContent&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatContent&lt;/span&gt;)',['../index.html#autotoc_md50',1,'']]],
  ['llama_5fmsgs_20msg_20chatdeltachunk_12',['&lt;span class=&quot;tt&quot;&gt;ChatDeltaChunk&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatDeltaChunk&lt;/span&gt;)',['../index.html#autotoc_md76',1,'']]],
  ['llama_5fmsgs_20msg_20chatmessage_13',['&lt;span class=&quot;tt&quot;&gt;ChatMessage&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatMessage&lt;/span&gt;)',['../index.html#autotoc_md49',1,'']]],
  ['llama_5fmsgs_20msg_20chatreasoningformat_14',['&lt;span class=&quot;tt&quot;&gt;ChatReasoningFormat&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatReasoningFormat&lt;/span&gt;)',['../index.html#autotoc_md54',1,'']]],
  ['llama_5fmsgs_20msg_20chatreqtool_15',['&lt;span class=&quot;tt&quot;&gt;ChatReqTool&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatReqTool&lt;/span&gt;)',['../index.html#autotoc_md52',1,'']]],
  ['llama_5fmsgs_20msg_20chattool_16',['&lt;span class=&quot;tt&quot;&gt;ChatTool&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatTool&lt;/span&gt;)',['../index.html#autotoc_md53',1,'']]],
  ['llama_5fmsgs_20msg_20chattoolcall_17',['&lt;span class=&quot;tt&quot;&gt;ChatToolCall&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatToolCall&lt;/span&gt;)',['../index.html#autotoc_md51',1,'']]],
  ['llama_5fmsgs_20msg_20decisionanswer_18',['&lt;span class=&quot;tt&quot;&gt;DecisionAnswer&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/DecisionAnswer&lt;/span&gt;)',['../index.html#autotoc_md65',1,'']]],
  ['llama_5fmsgs_20msg_20decisioninfo_19',['&lt;span class=&quot;tt&quot;&gt;DecisionInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/DecisionInfo&lt;/span&gt;)',['../index.html#autotoc_md63',1,'']]],
  ['llama_5fmsgs_20msg_20decisionquestion_20',['&lt;span class=&quot;tt&quot;&gt;DecisionQuestion&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/DecisionQuestion&lt;/span&gt;)',['../index.html#autotoc_md64',1,'']]],
  ['llama_5fmsgs_20msg_20generalinfo_21',['&lt;span class=&quot;tt&quot;&gt;GeneralInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/GeneralInfo&lt;/span&gt;)',['../index.html#autotoc_md56',1,'']]],
  ['llama_5fmsgs_20msg_20grammartrigger_22',['&lt;span class=&quot;tt&quot;&gt;GrammarTrigger&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/GrammarTrigger&lt;/span&gt;)',['../index.html#autotoc_md48',1,'']]],
  ['llama_5fmsgs_20msg_20logitbias_23',['&lt;span class=&quot;tt&quot;&gt;LogitBias&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LogitBias&lt;/span&gt;)',['../index.html#autotoc_md46',1,'']]],
  ['llama_5fmsgs_20msg_20logitbiasarray_24',['&lt;span class=&quot;tt&quot;&gt;LogitBiasArray&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LogitBiasArray&lt;/span&gt;)',['../index.html#autotoc_md47',1,'']]],
  ['llama_5fmsgs_20msg_20lora_25',['&lt;span class=&quot;tt&quot;&gt;LoRA&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LoRA&lt;/span&gt;)',['../index.html#autotoc_md80',1,'']]],
  ['llama_5fmsgs_20msg_20metadata_26',['&lt;span class=&quot;tt&quot;&gt;Metadata&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/Metadata&lt;/span&gt;)',['../index.html#autotoc_md55',1,'']]],
  ['llama_5fmsgs_20msg_20modelinfo_27',['&lt;span class=&quot;tt&quot;&gt;ModelInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ModelInfo&lt;/span&gt;)',['../index.html#autotoc_md57',1,'']]],
  ['llama_5fmsgs_20msg_20partialresponse_28',['&lt;span class=&quot;tt&quot;&gt;PartialResponse&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/PartialResponse&lt;/span&gt;)',['../index.html#autotoc_md67',1,'']]],
  ['llama_5fmsgs_20msg_20response_29',['&lt;span class=&quot;tt&quot;&gt;Response&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/Response&lt;/span&gt;)',['../index.html#autotoc_md66',1,'']]],
  ['llama_5fmsgs_20msg_20ropeinfo_30',['&lt;span class=&quot;tt&quot;&gt;RoPEInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/RoPEInfo&lt;/span&gt;)',['../index.html#autotoc_md59',1,'']]],
  ['llama_5fmsgs_20msg_20samplingconfig_31',['&lt;span class=&quot;tt&quot;&gt;SamplingConfig&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/SamplingConfig&lt;/span&gt;)',['../index.html#autotoc_md45',1,'']]],
  ['llama_5fmsgs_20msg_20samplinginfo_32',['&lt;span class=&quot;tt&quot;&gt;SamplingInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/SamplingInfo&lt;/span&gt;)',['../index.html#autotoc_md62',1,'']]],
  ['llama_5fmsgs_20msg_20tokenizerinfo_33',['&lt;span class=&quot;tt&quot;&gt;TokenizerInfo&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/TokenizerInfo&lt;/span&gt;)',['../index.html#autotoc_md60',1,'']]],
  ['llama_5fmsgs_20msg_20tokenprob_34',['&lt;span class=&quot;tt&quot;&gt;TokenProb&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/TokenProb&lt;/span&gt;)',['../index.html#autotoc_md68',1,'']]],
  ['llama_5fmsgs_20msg_20tokenprobarray_35',['&lt;span class=&quot;tt&quot;&gt;TokenProbArray&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/TokenProbArray&lt;/span&gt;)',['../index.html#autotoc_md69',1,'']]],
  ['llama_5fmsgs_20msg_20usagestats_36',['&lt;span class=&quot;tt&quot;&gt;UsageStats&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/UsageStats&lt;/span&gt;)',['../index.html#autotoc_md70',1,'']]],
  ['llama_5fros_37',['llama_ros',['../index.html',1,'']]],
  ['llama_5fros_20chain_38',['llama_ros (Chain)',['../index.html#autotoc_md92',1,'']]],
  ['llama_5fros_20llm_20rag_20reranker_39',['llama_ros (LLM + RAG + Reranker)',['../index.html#autotoc_md97',1,'']]],
  ['llama_5fros_20python_20launch_40',['llama_ros (Python Launch)',['../index.html#autotoc_md10',1,'']]],
  ['llama_5fros_20reranker_41',['llama_ros (Reranker)',['../index.html#autotoc_md96',1,'']]],
  ['llama_5fros_20speculative_20decoding_42',['llama_ros (Speculative Decoding)',['../index.html#autotoc_md13',1,'']]],
  ['llama_5fros_20stream_43',['llama_ros (Stream)',['../index.html#autotoc_md93',1,'']]],
  ['llama_5fros_20yaml_20config_44',['llama_ros (YAML Config)',['../index.html#autotoc_md11',1,'']]],
  ['llama_5fros_20yaml_20config_20model_20shards_45',['llama_ros (YAML Config + model shards)',['../index.html#autotoc_md12',1,'']]],
  ['llama_5fros_5fembeddings_20rag_46',['llama_ros_embeddings (RAG)',['../index.html#autotoc_md95',1,'']]],
  ['llava_47',['Generate Response (llava)',['../index.html#autotoc_md87',1,'']]],
  ['llava_5fros_48',['llava_ros',['../index.html#autotoc_md94',1,'']]],
  ['llava_5fros_20audio_49',['llava_ros (Audio)',['../index.html#autotoc_md16',1,'']]],
  ['llava_5fros_20python_20launch_50',['llava_ros (Python Launch)',['../index.html#autotoc_md14',1,'']]],
  ['llava_5fros_20yaml_20config_51',['llava_ros (YAML Config)',['../index.html#autotoc_md15',1,'']]],
  ['llm_20chat_20template_20rag_20reranking_20stream_52',['RAG Demo (LLM + chat template + RAG + Reranking + Stream)',['../index.html#autotoc_md112',1,'']]],
  ['llm_20demo_53',['LLM Demo',['../index.html#autotoc_md105',1,'']]],
  ['llm_20rag_20reranker_54',['llama_ros (LLM + RAG + Reranker)',['../index.html#autotoc_md97',1,'']]],
  ['logitbias_55',['&lt;span class=&quot;tt&quot;&gt;LogitBias&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LogitBias&lt;/span&gt;)',['../index.html#autotoc_md46',1,'']]],
  ['logitbias_20llama_5fmsgs_20msg_20logitbias_56',['&lt;span class=&quot;tt&quot;&gt;LogitBias&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LogitBias&lt;/span&gt;)',['../index.html#autotoc_md46',1,'']]],
  ['logitbiasarray_57',['&lt;span class=&quot;tt&quot;&gt;LogitBiasArray&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LogitBiasArray&lt;/span&gt;)',['../index.html#autotoc_md47',1,'']]],
  ['logitbiasarray_20llama_5fmsgs_20msg_20logitbiasarray_58',['&lt;span class=&quot;tt&quot;&gt;LogitBiasArray&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LogitBiasArray&lt;/span&gt;)',['../index.html#autotoc_md47',1,'']]],
  ['lora_59',['&lt;span class=&quot;tt&quot;&gt;LoRA&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LoRA&lt;/span&gt;)',['../index.html#autotoc_md80',1,'']]],
  ['lora_60',['LoRA Adapters (&lt;span class=&quot;tt&quot;&gt;lora.*&lt;/span&gt;)',['../index.html#autotoc_md43',1,'']]],
  ['lora_20adapters_61',['LoRA Adapters',['../index.html#autotoc_md81',1,'']]],
  ['lora_20adapters_20lora_62',['LoRA Adapters (&lt;span class=&quot;tt&quot;&gt;lora.*&lt;/span&gt;)',['../index.html#autotoc_md43',1,'']]],
  ['lora_20llama_5fmsgs_20msg_20lora_63',['&lt;span class=&quot;tt&quot;&gt;LoRA&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/LoRA&lt;/span&gt;)',['../index.html#autotoc_md80',1,'']]]
];
