var searchData=
[
  ['cache_0',['KV Cache (&lt;span class=&quot;tt&quot;&gt;cache.*&lt;/span&gt;)',['../index.html#autotoc_md32',1,'']]],
  ['cache_20cache_1',['KV Cache (&lt;span class=&quot;tt&quot;&gt;cache.*&lt;/span&gt;)',['../index.html#autotoc_md32',1,'']]],
  ['cache_20speculative_20ngram_5fcache_2',['Ngram-cache (&lt;span class=&quot;tt&quot;&gt;speculative.ngram_cache.*&lt;/span&gt;)',['../index.html#autotoc_md41',1,'']]],
  ['chain_3',['llama_ros (Chain)',['../index.html#autotoc_md92',1,'']]],
  ['chat_20audio_4',['chat_llama_ros (Chat + Audio)',['../index.html#autotoc_md99',1,'']]],
  ['chat_20audio_20demo_5',['Chat Audio Demo',['../index.html#autotoc_md118',1,'']]],
  ['chat_20completions_6',['Generate Chat Completions',['../index.html#autotoc_md88',1,'']]],
  ['chat_20multi_20audio_20demo_7',['Chat Multi-Audio Demo',['../index.html#autotoc_md119',1,'']]],
  ['chat_20multi_20image_20demo_8',['Chat Multi-Image Demo',['../index.html#autotoc_md115',1,'']]],
  ['chat_20multi_20image_20user_20input_20demo_9',['Chat Multi-Image (User Input) Demo',['../index.html#autotoc_md116',1,'']]],
  ['chat_20prompt_10',['Prompt &amp;amp; Chat (&lt;span class=&quot;tt&quot;&gt;prompt.*&lt;/span&gt;)',['../index.html#autotoc_md42',1,'']]],
  ['chat_20reasoning_20demo_20deepseek_20r1_11',['Chat Reasoning Demo (DeepSeek-R1)',['../index.html#autotoc_md123',1,'']]],
  ['chat_20structured_20output_20demo_12',['Chat Structured Output Demo',['../index.html#autotoc_md120',1,'']]],
  ['chat_20template_20demo_13',['Chat Template Demo',['../index.html#autotoc_md113',1,'']]],
  ['chat_20template_20rag_20reranking_20stream_14',['RAG Demo (LLM + chat template + RAG + Reranking + Stream)',['../index.html#autotoc_md112',1,'']]],
  ['chat_20tools_20demo_15',['Chat Tools Demo',['../index.html#autotoc_md121',1,'']]],
  ['chat_20vlm_16',['chat_llama_ros (Chat + VLM)',['../index.html#autotoc_md98',1,'']]],
  ['chat_5fllama_5fros_20agent_17',['chat_llama_ros (Agent)',['../index.html#autotoc_md103',1,'']]],
  ['chat_5fllama_5fros_20chat_20audio_18',['chat_llama_ros (Chat + Audio)',['../index.html#autotoc_md99',1,'']]],
  ['chat_5fllama_5fros_20chat_20vlm_19',['chat_llama_ros (Chat + VLM)',['../index.html#autotoc_md98',1,'']]],
  ['chat_5fllama_5fros_20reasoning_20',['chat_llama_ros (Reasoning)',['../index.html#autotoc_md102',1,'']]],
  ['chat_5fllama_5fros_20structured_20output_21',['chat_llama_ros (Structured output)',['../index.html#autotoc_md100',1,'']]],
  ['chat_5fllama_5fros_20tools_22',['chat_llama_ros (Tools)',['../index.html#autotoc_md101',1,'']]],
  ['chatchoice_23',['&lt;span class=&quot;tt&quot;&gt;ChatChoice&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatChoice&lt;/span&gt;)',['../index.html#autotoc_md73',1,'']]],
  ['chatchoice_20llama_5fmsgs_20msg_20chatchoice_24',['&lt;span class=&quot;tt&quot;&gt;ChatChoice&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatChoice&lt;/span&gt;)',['../index.html#autotoc_md73',1,'']]],
  ['chatchoicechunk_25',['&lt;span class=&quot;tt&quot;&gt;ChatChoiceChunk&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatChoiceChunk&lt;/span&gt;)',['../index.html#autotoc_md75',1,'']]],
  ['chatchoicechunk_20llama_5fmsgs_20msg_20chatchoicechunk_26',['&lt;span class=&quot;tt&quot;&gt;ChatChoiceChunk&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatChoiceChunk&lt;/span&gt;)',['../index.html#autotoc_md75',1,'']]],
  ['chatcontent_27',['&lt;span class=&quot;tt&quot;&gt;ChatContent&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatContent&lt;/span&gt;)',['../index.html#autotoc_md50',1,'']]],
  ['chatcontent_20llama_5fmsgs_20msg_20chatcontent_28',['&lt;span class=&quot;tt&quot;&gt;ChatContent&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatContent&lt;/span&gt;)',['../index.html#autotoc_md50',1,'']]],
  ['chatdeltachunk_29',['&lt;span class=&quot;tt&quot;&gt;ChatDeltaChunk&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatDeltaChunk&lt;/span&gt;)',['../index.html#autotoc_md76',1,'']]],
  ['chatdeltachunk_20llama_5fmsgs_20msg_20chatdeltachunk_30',['&lt;span class=&quot;tt&quot;&gt;ChatDeltaChunk&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatDeltaChunk&lt;/span&gt;)',['../index.html#autotoc_md76',1,'']]],
  ['chatmessage_31',['&lt;span class=&quot;tt&quot;&gt;ChatMessage&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatMessage&lt;/span&gt;)',['../index.html#autotoc_md49',1,'']]],
  ['chatmessage_20llama_5fmsgs_20msg_20chatmessage_32',['&lt;span class=&quot;tt&quot;&gt;ChatMessage&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatMessage&lt;/span&gt;)',['../index.html#autotoc_md49',1,'']]],
  ['chatreasoningformat_33',['&lt;span class=&quot;tt&quot;&gt;ChatReasoningFormat&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatReasoningFormat&lt;/span&gt;)',['../index.html#autotoc_md54',1,'']]],
  ['chatreasoningformat_20llama_5fmsgs_20msg_20chatreasoningformat_34',['&lt;span class=&quot;tt&quot;&gt;ChatReasoningFormat&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatReasoningFormat&lt;/span&gt;)',['../index.html#autotoc_md54',1,'']]],
  ['chatreqtool_35',['&lt;span class=&quot;tt&quot;&gt;ChatReqTool&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatReqTool&lt;/span&gt;)',['../index.html#autotoc_md52',1,'']]],
  ['chatreqtool_20llama_5fmsgs_20msg_20chatreqtool_36',['&lt;span class=&quot;tt&quot;&gt;ChatReqTool&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatReqTool&lt;/span&gt;)',['../index.html#autotoc_md52',1,'']]],
  ['chattool_37',['&lt;span class=&quot;tt&quot;&gt;ChatTool&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatTool&lt;/span&gt;)',['../index.html#autotoc_md53',1,'']]],
  ['chattool_20llama_5fmsgs_20msg_20chattool_38',['&lt;span class=&quot;tt&quot;&gt;ChatTool&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatTool&lt;/span&gt;)',['../index.html#autotoc_md53',1,'']]],
  ['chattoolcall_39',['&lt;span class=&quot;tt&quot;&gt;ChatToolCall&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatToolCall&lt;/span&gt;)',['../index.html#autotoc_md51',1,'']]],
  ['chattoolcall_20llama_5fmsgs_20msg_20chattoolcall_40',['&lt;span class=&quot;tt&quot;&gt;ChatToolCall&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/ChatToolCall&lt;/span&gt;)',['../index.html#autotoc_md51',1,'']]],
  ['clients_41',['ROS 2 Clients',['../index.html#autotoc_md82',1,'']]],
  ['completions_42',['Generate Chat Completions',['../index.html#autotoc_md88',1,'']]],
  ['config_43',['Config',['../index.html#autotoc_md11',1,'llama_ros (YAML Config)'],['../index.html#autotoc_md15',1,'llava_ros (YAML Config)']]],
  ['config_20model_20shards_44',['llama_ros (YAML Config + model shards)',['../index.html#autotoc_md12',1,'']]],
  ['contents_45',['Table of Contents',['../index.html#autotoc_md1',1,'']]],
  ['context_46',['Context / Inference (&lt;span class=&quot;tt&quot;&gt;context.*&lt;/span&gt;)',['../index.html#autotoc_md21',1,'']]],
  ['context_20inference_20context_47',['Context / Inference (&lt;span class=&quot;tt&quot;&gt;context.*&lt;/span&gt;)',['../index.html#autotoc_md21',1,'']]],
  ['control_20vector_20control_5fvector_48',['Control Vector (&lt;span class=&quot;tt&quot;&gt;control_vector.*&lt;/span&gt;)',['../index.html#autotoc_md24',1,'']]],
  ['control_5fvector_49',['Control Vector (&lt;span class=&quot;tt&quot;&gt;control_vector.*&lt;/span&gt;)',['../index.html#autotoc_md24',1,'']]],
  ['cpu_50',['CPU (&lt;span class=&quot;tt&quot;&gt;cpu.*&lt;/span&gt;)',['../index.html#autotoc_md27',1,'']]],
  ['cpu_20and_20speculative_20draft_20cpu_5fbatch_51',['Draft CPU (&lt;span class=&quot;tt&quot;&gt;speculative.draft.cpu.*&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;speculative.draft.cpu_batch.*&lt;/span&gt;)',['../index.html#autotoc_md36',1,'']]],
  ['cpu_20batch_20cpu_5fbatch_52',['CPU Batch (&lt;span class=&quot;tt&quot;&gt;cpu_batch.*&lt;/span&gt;)',['../index.html#autotoc_md28',1,'']]],
  ['cpu_20cpu_53',['CPU (&lt;span class=&quot;tt&quot;&gt;cpu.*&lt;/span&gt;)',['../index.html#autotoc_md27',1,'']]],
  ['cpu_20speculative_20draft_20cpu_20and_20speculative_20draft_20cpu_5fbatch_54',['Draft CPU (&lt;span class=&quot;tt&quot;&gt;speculative.draft.cpu.*&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;speculative.draft.cpu_batch.*&lt;/span&gt;)',['../index.html#autotoc_md36',1,'']]],
  ['cpu_5fbatch_55',['cpu_batch',['../index.html#autotoc_md28',1,'CPU Batch (&lt;span class=&quot;tt&quot;&gt;cpu_batch.*&lt;/span&gt;)'],['../index.html#autotoc_md36',1,'Draft CPU (&lt;span class=&quot;tt&quot;&gt;speculative.draft.cpu.*&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;speculative.draft.cpu_batch.*&lt;/span&gt;)']]]
];
