var searchData=
[
  ['cache_0',['KV Cache (&lt;span class=&quot;tt&quot;&gt;cache.*&lt;/span&gt;)',['../index.html#autotoc_md29',1,'']]],
  ['cache_20cache_1',['KV Cache (&lt;span class=&quot;tt&quot;&gt;cache.*&lt;/span&gt;)',['../index.html#autotoc_md29',1,'']]],
  ['cache_20speculative_20ngram_5fcache_2',['Ngram-cache (&lt;span class=&quot;tt&quot;&gt;speculative.ngram_cache.*&lt;/span&gt;)',['../index.html#autotoc_md37',1,'']]],
  ['chain_3',['llama_ros (Chain)',['../index.html#autotoc_md54',1,'']]],
  ['chat_20audio_4',['chat_llama_ros (Chat + Audio)',['../index.html#autotoc_md61',1,'']]],
  ['chat_20audio_20demo_5',['Chat Audio Demo',['../index.html#autotoc_md78',1,'']]],
  ['chat_20completions_6',['Generate Chat Completions',['../index.html#autotoc_md50',1,'']]],
  ['chat_20multi_20audio_20demo_7',['Chat Multi-Audio Demo',['../index.html#autotoc_md79',1,'']]],
  ['chat_20multi_20image_20demo_8',['Chat Multi-Image Demo',['../index.html#autotoc_md75',1,'']]],
  ['chat_20multi_20image_20user_20input_20demo_9',['Chat Multi-Image (User Input) Demo',['../index.html#autotoc_md76',1,'']]],
  ['chat_20prompt_10',['Prompt &amp;amp; Chat (&lt;span class=&quot;tt&quot;&gt;prompt.*&lt;/span&gt;)',['../index.html#autotoc_md38',1,'']]],
  ['chat_20reasoning_20demo_20deepseek_20r1_11',['Chat Reasoning Demo (DeepSeek-R1)',['../index.html#autotoc_md83',1,'']]],
  ['chat_20structured_20output_20demo_12',['Chat Structured Output Demo',['../index.html#autotoc_md80',1,'']]],
  ['chat_20template_20demo_13',['Chat Template Demo',['../index.html#autotoc_md73',1,'']]],
  ['chat_20template_20rag_20reranking_20stream_14',['RAG Demo (LLM + chat template + RAG + Reranking + Stream)',['../index.html#autotoc_md72',1,'']]],
  ['chat_20tools_20demo_15',['Chat Tools Demo',['../index.html#autotoc_md81',1,'']]],
  ['chat_20vlm_16',['chat_llama_ros (Chat + VLM)',['../index.html#autotoc_md60',1,'']]],
  ['chat_5fllama_5fros_20agent_17',['chat_llama_ros (Agent)',['../index.html#autotoc_md65',1,'']]],
  ['chat_5fllama_5fros_20chat_20audio_18',['chat_llama_ros (Chat + Audio)',['../index.html#autotoc_md61',1,'']]],
  ['chat_5fllama_5fros_20chat_20vlm_19',['chat_llama_ros (Chat + VLM)',['../index.html#autotoc_md60',1,'']]],
  ['chat_5fllama_5fros_20reasoning_20',['chat_llama_ros (Reasoning)',['../index.html#autotoc_md64',1,'']]],
  ['chat_5fllama_5fros_20structured_20output_21',['chat_llama_ros (Structured output)',['../index.html#autotoc_md62',1,'']]],
  ['chat_5fllama_5fros_20tools_22',['chat_llama_ros (Tools)',['../index.html#autotoc_md63',1,'']]],
  ['clients_23',['ROS 2 Clients',['../index.html#autotoc_md44',1,'']]],
  ['completions_24',['Generate Chat Completions',['../index.html#autotoc_md50',1,'']]],
  ['config_25',['Config',['../index.html#autotoc_md11',1,'llama_ros (YAML Config)'],['../index.html#autotoc_md15',1,'llava_ros (YAML Config)']]],
  ['config_20model_20shards_26',['llama_ros (YAML Config + model shards)',['../index.html#autotoc_md12',1,'']]],
  ['contents_27',['Table of Contents',['../index.html#autotoc_md1',1,'']]],
  ['context_28',['Context / Inference (&lt;span class=&quot;tt&quot;&gt;context.*&lt;/span&gt;)',['../index.html#autotoc_md21',1,'']]],
  ['context_20inference_20context_29',['Context / Inference (&lt;span class=&quot;tt&quot;&gt;context.*&lt;/span&gt;)',['../index.html#autotoc_md21',1,'']]],
  ['cpu_30',['CPU (&lt;span class=&quot;tt&quot;&gt;cpu.*&lt;/span&gt;)',['../index.html#autotoc_md24',1,'']]],
  ['cpu_20batch_20cpu_5fbatch_31',['CPU Batch (&lt;span class=&quot;tt&quot;&gt;cpu_batch.*&lt;/span&gt;)',['../index.html#autotoc_md25',1,'']]],
  ['cpu_20cpu_32',['CPU (&lt;span class=&quot;tt&quot;&gt;cpu.*&lt;/span&gt;)',['../index.html#autotoc_md24',1,'']]],
  ['cpu_5fbatch_33',['CPU Batch (&lt;span class=&quot;tt&quot;&gt;cpu_batch.*&lt;/span&gt;)',['../index.html#autotoc_md25',1,'']]]
];
