var searchData=
[
  ['langchain_0',['LangChain',['../index.html#autotoc_md47',1,'']]],
  ['launch_1',['Launch',['../index.html#autotoc_md10',1,'llama_ros (Python Launch)'],['../index.html#autotoc_md14',1,'llava_ros (Python Launch)']]],
  ['launch_2',['launch',['../index.html#autotoc_md7',1,'']]],
  ['launch_20files_3',['Launch Files',['../index.html#autotoc_md9',1,'']]],
  ['llama_5fcli_4',['llama_cli',['../index.html#autotoc_md6',1,'']]],
  ['llama_5fmsgs_20action_20generatechatcompletions_5',['&lt;span class=&quot;tt&quot;&gt;GenerateChatCompletions&lt;/span&gt; Goal (&lt;span class=&quot;tt&quot;&gt;llama_msgs/action/GenerateChatCompletions&lt;/span&gt;)',['../index.html#autotoc_md36',1,'']]],
  ['llama_5fmsgs_20msg_20samplingconfig_6',['&lt;span class=&quot;tt&quot;&gt;SamplingConfig&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;llama_msgs/msg/SamplingConfig&lt;/span&gt;)',['../index.html#autotoc_md35',1,'']]],
  ['llama_5fros_7',['llama_ros',['../index.html',1,'']]],
  ['llama_5fros_20chain_8',['llama_ros (Chain)',['../index.html#autotoc_md48',1,'']]],
  ['llama_5fros_20llm_20rag_20reranker_9',['llama_ros (LLM + RAG + Reranker)',['../index.html#autotoc_md53',1,'']]],
  ['llama_5fros_20python_20launch_10',['llama_ros (Python Launch)',['../index.html#autotoc_md10',1,'']]],
  ['llama_5fros_20reranker_11',['llama_ros (Reranker)',['../index.html#autotoc_md52',1,'']]],
  ['llama_5fros_20speculative_20decoding_12',['llama_ros (Speculative Decoding)',['../index.html#autotoc_md13',1,'']]],
  ['llama_5fros_20stream_13',['llama_ros (Stream)',['../index.html#autotoc_md49',1,'']]],
  ['llama_5fros_20yaml_20config_14',['llama_ros (YAML Config)',['../index.html#autotoc_md11',1,'']]],
  ['llama_5fros_20yaml_20config_20model_20shards_15',['llama_ros (YAML Config + model shards)',['../index.html#autotoc_md12',1,'']]],
  ['llama_5fros_5fembeddings_20rag_16',['llama_ros_embeddings (RAG)',['../index.html#autotoc_md51',1,'']]],
  ['llava_17',['Generate Response (llava)',['../index.html#autotoc_md43',1,'']]],
  ['llava_5fros_18',['llava_ros',['../index.html#autotoc_md50',1,'']]],
  ['llava_5fros_20audio_19',['llava_ros (Audio)',['../index.html#autotoc_md16',1,'']]],
  ['llava_5fros_20python_20launch_20',['llava_ros (Python Launch)',['../index.html#autotoc_md14',1,'']]],
  ['llava_5fros_20yaml_20config_21',['llava_ros (YAML Config)',['../index.html#autotoc_md15',1,'']]],
  ['llm_20chat_20template_20rag_20reranking_20stream_22',['RAG Demo (LLM + chat template + RAG + Reranking + Stream)',['../index.html#autotoc_md65',1,'']]],
  ['llm_20demo_23',['LLM Demo',['../index.html#autotoc_md61',1,'']]],
  ['llm_20rag_20reranker_24',['llama_ros (LLM + RAG + Reranker)',['../index.html#autotoc_md53',1,'']]],
  ['lora_25',['LoRA Adapters (&lt;span class=&quot;tt&quot;&gt;lora.*&lt;/span&gt;)',['../index.html#autotoc_md33',1,'']]],
  ['lora_20adapters_26',['LoRA Adapters',['../index.html#autotoc_md37',1,'']]],
  ['lora_20adapters_20lora_27',['LoRA Adapters (&lt;span class=&quot;tt&quot;&gt;lora.*&lt;/span&gt;)',['../index.html#autotoc_md33',1,'']]]
];
