var searchData=
[
  ['langchain_0',['LangChain',['../index.html#autotoc_md22',1,'']]],
  ['launch_1',['Launch',['../index.html#autotoc_md10',1,'llama_ros (Python Launch)'],['../index.html#autotoc_md13',1,'llava_ros (Python Launch)']]],
  ['launch_2',['launch',['../index.html#autotoc_md7',1,'']]],
  ['launch_20files_3',['Launch Files',['../index.html#autotoc_md9',1,'']]],
  ['launch_2epy_4',['launch.py',['../launch_8py.html',1,'']]],
  ['launch_5fllm_5',['launch_llm',['../namespacellama__cli_1_1api.html#ad208ac7099874aa35e0670e6237fe312',1,'llama_cli::api']]],
  ['launchverb_6',['LaunchVerb',['../classllama__cli_1_1verb_1_1launch_1_1LaunchVerb.html',1,'llama_cli::verb::launch']]],
  ['license_7',['license',['../namespacesetup.html#a8ed6f50a28bd6a8794f8e1153baa6de9',1,'setup']]],
  ['list_5floras_8',['list_loras',['../classllama__ros_1_1Llama.html#a42ebfca7305a94a0acd4ac25c14b25df',1,'llama_ros::Llama']]],
  ['list_5floras_5fservice_5f_9',['list_loras_service_',['../classllama__ros_1_1LlamaNode.html#ae48613d70306d3100ea7d332b0a5040c',1,'llama_ros::LlamaNode']]],
  ['list_5floras_5fservice_5fcallback_10',['list_loras_service_callback',['../classllama__ros_1_1LlamaNode.html#a5a79bd20864384f74c8d6faa9a8d2386',1,'llama_ros::LlamaNode']]],
  ['llama_11',['Llama',['../classllama__ros_1_1Llama.html',1,'llama_ros::Llama'],['../classllama__ros_1_1Llama.html#ac51bb5f0f3bfec7190ea081a04ae4824',1,'llama_ros::Llama::Llama()']]],
  ['llama_12',['llama',['../classllama__ros_1_1LlamaNode.html#add09929e4bb019eac008da2bdd4b8427',1,'llama_ros::LlamaNode']]],
  ['llama_2ecpp_13',['llama.cpp',['../llama_8cpp.html',1,'']]],
  ['llama_2ehpp_14',['llama.hpp',['../llama_8hpp.html',1,'']]],
  ['llama_2epy_15',['llama.py',['../llama_8py.html',1,'']]],
  ['llama_5fbringup_16',['llama_bringup',['../namespacellama__bringup.html',1,'']]],
  ['llama_5fbringup_3a_3autils_17',['utils',['../namespacellama__bringup_1_1utils.html',1,'llama_bringup']]],
  ['llama_5fcli_18',['llama_cli',['../namespacellama__cli.html',1,'llama_cli'],['../index.html#autotoc_md6',1,'llama_cli']]],
  ['llama_5fcli_3a_3aapi_19',['api',['../namespacellama__cli_1_1api.html',1,'llama_cli']]],
  ['llama_5fcli_3a_3acommand_20',['command',['../namespacellama__cli_1_1command.html',1,'llama_cli']]],
  ['llama_5fcli_3a_3acommand_3a_3allama_21',['llama',['../namespacellama__cli_1_1command_1_1llama.html',1,'llama_cli::command']]],
  ['llama_5fcli_3a_3averb_22',['verb',['../namespacellama__cli_1_1verb.html',1,'llama_cli']]],
  ['llama_5fcli_3a_3averb_3a_3alaunch_23',['launch',['../namespacellama__cli_1_1verb_1_1launch.html',1,'llama_cli::verb']]],
  ['llama_5fcli_3a_3averb_3a_3aprompt_24',['prompt',['../namespacellama__cli_1_1verb_1_1prompt.html',1,'llama_cli::verb']]],
  ['llama_5fclient_25',['llama_client',['../classllama__ros_1_1langchain_1_1llama__ros__common_1_1LlamaROSCommon.html#a7b501bbb960ff2ad744219f9d4c79111',1,'llama_ros.langchain.llama_ros_common.LlamaROSCommon.llama_client'],['../classllama__ros_1_1langchain_1_1llama__ros__embeddings_1_1LlamaROSEmbeddings.html#aab2a92bed23738f29c2bd0681e14641e',1,'llama_ros.langchain.llama_ros_embeddings.LlamaROSEmbeddings.llama_client']]],
  ['llama_5fclient_5fnode_2epy_26',['llama_client_node.py',['../llama__client__node_8py.html',1,'']]],
  ['llama_5fdemo_5fnode_2epy_27',['llama_demo_node.py',['../llama__demo__node_8py.html',1,'']]],
  ['llama_5fdemos_28',['llama_demos',['../namespacellama__demos.html',1,'']]],
  ['llama_5fdemos_3a_3achatllama_5fdemo_5fnode_29',['chatllama_demo_node',['../namespacellama__demos_1_1chatllama__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3allama_5fdemo_5fnode_30',['llama_demo_node',['../namespacellama__demos_1_1llama__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3allama_5fembeddings_5fdemo_5fnode_31',['llama_embeddings_demo_node',['../namespacellama__demos_1_1llama__embeddings__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3allama_5frag_5fdemo_5fnode_32',['llama_rag_demo_node',['../namespacellama__demos_1_1llama__rag__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3allama_5frerank_5fdemo_5fnode_33',['llama_rerank_demo_node',['../namespacellama__demos_1_1llama__rerank__demo__node.html',1,'llama_demos']]],
  ['llama_5fdemos_3a_3allava_5fdemo_5fnode_34',['llava_demo_node',['../namespacellama__demos_1_1llava__demo__node.html',1,'llama_demos']]],
  ['llama_5fembeddings_5fdemo_5fnode_2epy_35',['llama_embeddings_demo_node.py',['../llama__embeddings__demo__node_8py.html',1,'']]],
  ['llama_5flog_5ferror_36',['LLAMA_LOG_ERROR',['../llama_8hpp.html#af57cb87dacb596fda45658e510d9ac53',1,'llama.hpp']]],
  ['llama_5flog_5finfo_37',['LLAMA_LOG_INFO',['../llama_8hpp.html#a59f368b6a6adf649e06afe07ef10508b',1,'llama.hpp']]],
  ['llama_5flog_5fwarn_38',['LLAMA_LOG_WARN',['../llama_8hpp.html#a7903d2c72fa8e8887bad72cb85d27e8c',1,'llama.hpp']]],
  ['llama_5fmain_2ecpp_39',['llama_main.cpp',['../llama__main_8cpp.html',1,'']]],
  ['llama_5fnode_2ecpp_40',['llama_node.cpp',['../llama__node_8cpp.html',1,'']]],
  ['llama_5fnode_2ehpp_41',['llama_node.hpp',['../llama__node_8hpp.html',1,'']]],
  ['llama_5fparams_42',['llama_params',['../structllama__utils_1_1llama__params.html',1,'llama_utils']]],
  ['llama_5fparams_2ecpp_43',['llama_params.cpp',['../llama__params_8cpp.html',1,'']]],
  ['llama_5fparams_2ehpp_44',['llama_params.hpp',['../llama__params_8hpp.html',1,'']]],
  ['llama_5frag_5fdemo_5fnode_2epy_45',['llama_rag_demo_node.py',['../llama__rag__demo__node_8py.html',1,'']]],
  ['llama_5frerank_5fdemo_5fnode_2epy_46',['llama_rerank_demo_node.py',['../llama__rerank__demo__node_8py.html',1,'']]],
  ['llama_5fros_47',['llama_ros',['../namespacellama__ros.html',1,'llama_ros'],['../index.html',1,'llama_ros']]],
  ['llama_5fros_20chain_48',['llama_ros (Chain)',['../index.html#autotoc_md23',1,'']]],
  ['llama_5fros_20llm_20rag_20reranker_49',['llama_ros (LLM + RAG + Reranker)',['../index.html#autotoc_md28',1,'']]],
  ['llama_5fros_20python_20launch_50',['llama_ros (Python Launch)',['../index.html#autotoc_md10',1,'']]],
  ['llama_5fros_20renranker_51',['llama_ros (Renranker)',['../index.html#autotoc_md27',1,'']]],
  ['llama_5fros_20stream_52',['llama_ros (Stream)',['../index.html#autotoc_md24',1,'']]],
  ['llama_5fros_20yaml_20config_53',['llama_ros (YAML Config)',['../index.html#autotoc_md11',1,'']]],
  ['llama_5fros_20yaml_20config_20model_20shards_54',['llama_ros (YAML Config + model shards)',['../index.html#autotoc_md12',1,'']]],
  ['llama_5fros_2epy_55',['llama_ros.py',['../llama__ros_8py.html',1,'']]],
  ['llama_5fros_3a_3alangchain_56',['langchain',['../namespacellama__ros_1_1langchain.html',1,'llama_ros']]],
  ['llama_5fros_3a_3alangchain_3a_3achat_5fllama_5fros_57',['chat_llama_ros',['../namespacellama__ros_1_1langchain_1_1chat__llama__ros.html',1,'llama_ros::langchain']]],
  ['llama_5fros_3a_3alangchain_3a_3achat_5fprompt_5fformatter_58',['chat_prompt_formatter',['../namespacellama__ros_1_1langchain_1_1chat__prompt__formatter.html',1,'llama_ros::langchain']]],
  ['llama_5fros_3a_3alangchain_3a_3allama_5fros_59',['llama_ros',['../namespacellama__ros_1_1langchain_1_1llama__ros.html',1,'llama_ros::langchain']]],
  ['llama_5fros_3a_3alangchain_3a_3allama_5fros_5fcommon_60',['llama_ros_common',['../namespacellama__ros_1_1langchain_1_1llama__ros__common.html',1,'llama_ros::langchain']]],
  ['llama_5fros_3a_3alangchain_3a_3allama_5fros_5fembeddings_61',['llama_ros_embeddings',['../namespacellama__ros_1_1langchain_1_1llama__ros__embeddings.html',1,'llama_ros::langchain']]],
  ['llama_5fros_3a_3alangchain_3a_3allama_5fros_5freranker_62',['llama_ros_reranker',['../namespacellama__ros_1_1langchain_1_1llama__ros__reranker.html',1,'llama_ros::langchain']]],
  ['llama_5fros_3a_3allama_5fclient_5fnode_63',['llama_client_node',['../namespacellama__ros_1_1llama__client__node.html',1,'llama_ros']]],
  ['llama_5fros_5fcommon_2epy_64',['llama_ros_common.py',['../llama__ros__common_8py.html',1,'']]],
  ['llama_5fros_5fembeddings_20rag_65',['llama_ros_embeddings (RAG)',['../index.html#autotoc_md26',1,'']]],
  ['llama_5fros_5fembeddings_2epy_66',['llama_ros_embeddings.py',['../llama__ros__embeddings_8py.html',1,'']]],
  ['llama_5fros_5freranker_2epy_67',['llama_ros_reranker.py',['../llama__ros__reranker_8py.html',1,'']]],
  ['llama_5futils_68',['llama_utils',['../namespacellama__utils.html',1,'']]],
  ['llamaclientnode_69',['LlamaClientNode',['../classllama__ros_1_1llama__client__node_1_1LlamaClientNode.html',1,'llama_ros::llama_client_node']]],
  ['llamacommand_70',['LlamaCommand',['../classllama__cli_1_1command_1_1llama_1_1LlamaCommand.html',1,'llama_cli::command::llama']]],
  ['llamademonode_71',['LlamaDemoNode',['../classllama__demos_1_1llama__demo__node_1_1LlamaDemoNode.html',1,'llama_demos::llama_demo_node']]],
  ['llamaembeddinsdemonode_72',['LlamaEmbeddinsDemoNode',['../classllama__demos_1_1llama__embeddings__demo__node_1_1LlamaEmbeddinsDemoNode.html',1,'llama_demos::llama_embeddings_demo_node']]],
  ['llamanode_73',['LlamaNode',['../classllama__ros_1_1LlamaNode.html',1,'llama_ros::LlamaNode'],['../classllama__ros_1_1LlamaNode.html#adc90c82214422e4d5c11bfc480e5ff93',1,'llama_ros::LlamaNode::LlamaNode()']]],
  ['llamaros_74',['LlamaROS',['../classllama__ros_1_1langchain_1_1llama__ros_1_1LlamaROS.html',1,'llama_ros::langchain::llama_ros']]],
  ['llamaroscommon_75',['LlamaROSCommon',['../classllama__ros_1_1langchain_1_1llama__ros__common_1_1LlamaROSCommon.html',1,'llama_ros::langchain::llama_ros_common']]],
  ['llamarosembeddings_76',['LlamaROSEmbeddings',['../classllama__ros_1_1langchain_1_1llama__ros__embeddings_1_1LlamaROSEmbeddings.html',1,'llama_ros::langchain::llama_ros_embeddings']]],
  ['llamarosreranker_77',['LlamaROSReranker',['../classllama__ros_1_1langchain_1_1llama__ros__reranker_1_1LlamaROSReranker.html',1,'llama_ros::langchain::llama_ros_reranker']]],
  ['llava_78',['Llava',['../classllava__ros_1_1Llava.html',1,'llava_ros::Llava'],['../classllava__ros_1_1Llava.html#a59771981839ee5e61e612d0a81bb880c',1,'llava_ros::Llava::Llava()']]],
  ['llava_79',['Generate Response (llava)',['../index.html#autotoc_md21',1,'']]],
  ['llava_2ecpp_80',['llava.cpp',['../llava_8cpp.html',1,'']]],
  ['llava_2ehpp_81',['llava.hpp',['../llava_8hpp.html',1,'']]],
  ['llava_5fdemo_5fnode_2epy_82',['llava_demo_node.py',['../llava__demo__node_8py.html',1,'']]],
  ['llava_5fmain_2ecpp_83',['llava_main.cpp',['../llava__main_8cpp.html',1,'']]],
  ['llava_5fnode_2ecpp_84',['llava_node.cpp',['../llava__node_8cpp.html',1,'']]],
  ['llava_5fnode_2ehpp_85',['llava_node.hpp',['../llava__node_8hpp.html',1,'']]],
  ['llava_5fparams_86',['llava_params',['../structllava__ros_1_1llava__params.html',1,'llava_ros::llava_params'],['../structllama__utils_1_1llama__params.html#a146064e8246040ab2ca13051e4d0287e',1,'llama_utils::llama_params::llava_params'],['../classllava__ros_1_1Llava.html#a71bd48235f4af15b9e5742cac2a9c189',1,'llava_ros::Llava::llava_params']]],
  ['llava_5fros_87',['llava_ros',['../namespacellava__ros.html',1,'llava_ros'],['../index.html#autotoc_md25',1,'llava_ros']]],
  ['llava_5fros_20python_20launch_88',['llava_ros (Python Launch)',['../index.html#autotoc_md13',1,'']]],
  ['llava_5fros_20yaml_20config_89',['llava_ros (YAML Config)',['../index.html#autotoc_md14',1,'']]],
  ['llavademonode_90',['LlavaDemoNode',['../classllama__demos_1_1llava__demo__node_1_1LlavaDemoNode.html',1,'llama_demos::llava_demo_node']]],
  ['llavanode_91',['LlavaNode',['../classllava__ros_1_1LlavaNode.html',1,'llava_ros::LlavaNode'],['../classllava__ros_1_1LlavaNode.html#aeeaefad9b9adeebe6d58e668693f21e4',1,'llava_ros::LlavaNode::LlavaNode()']]],
  ['llm_20chat_20template_20rag_20reranking_20stream_92',['Full Demo (LLM + chat template + RAG + Reranking + Stream)',['../index.html#autotoc_md36',1,'']]],
  ['llm_20demo_93',['LLM Demo',['../index.html#autotoc_md31',1,'']]],
  ['llm_20rag_20reranker_94',['llama_ros (LLM + RAG + Reranker)',['../index.html#autotoc_md28',1,'']]],
  ['load_5fimage_95',['load_image',['../classllava__ros_1_1Llava.html#a4c71bb5343835c82361617541ea5c993',1,'llava_ros::Llava']]],
  ['load_5fimage_5ffrom_5furl_96',['load_image_from_url',['../classllama__demos_1_1llava__demo__node_1_1LlavaDemoNode.html#a16886789c5f1276f1cceff40be75f5fc',1,'llama_demos::llava_demo_node::LlavaDemoNode']]],
  ['load_5fprompt_97',['load_prompt',['../classllama__ros_1_1Llama.html#a8ffa3d65b3a1ddea7e1708a25c8e4351',1,'llama_ros::Llama::load_prompt()'],['../classllava__ros_1_1Llava.html#aadee9a7a0d2f7461d7ed57cdb8326277',1,'llava_ros::Llava::load_prompt()']]],
  ['load_5fprompt_5ftype_98',['load_prompt_type',['../namespacellama__bringup_1_1utils.html#a156a8352d832e1d98e764122cfce2fbb',1,'llama_bringup::utils']]],
  ['loader_99',['loader',['../namespacellama__demos_1_1llama__rag__demo__node.html#ae54d07ee5b138bd488cf2855403b33c2',1,'llama_demos::llama_rag_demo_node']]],
  ['logit_5fbias_100',['logit_bias',['../classllama__ros_1_1langchain_1_1llama__ros__common_1_1LlamaROSCommon.html#afcc2316b7f8873d81004e723699caee6',1,'llama_ros::langchain::llama_ros_common::LlamaROSCommon']]],
  ['lora_101',['lora',['../structlora.html',1,'']]],
  ['lora_20adapters_102',['LoRA Adapters',['../index.html#autotoc_md15',1,'']]],
  ['lora_5fadapters_103',['lora_adapters',['../classllama__ros_1_1Llama.html#afd70a1fbaa075639cd32745c076524b7',1,'llama_ros::Llama']]]
];
