/**:
  ros__parameters:
    n_ctx: 2048
    n_batch: 1024
    n_predict: 2048
    n_gpu_layers: 0
    cpu:
      n_threads: 1
    embedding: true
    model:
      repo: second-state/All-MiniLM-L6-v2-Embedding-GGUF
      filename: all-MiniLM-L6-v2-ggml-model-f16.gguf
