/**:
  ros__parameters:
    # Model parameters
    model:
      repo: second-state/All-MiniLM-L6-v2-Embedding-GGUF
      filename: all-MiniLM-L6-v2-ggml-model-f16.gguf

    # Context / inference parameters
    context:
      n_ctx: 2048
      n_batch: 1024
      n_predict: 2048
      embedding: true

    # GPU / backend parameters
    gpu:
      n_gpu_layers: 0

    # CPU parameters
    cpu:
      n_threads: 1
