/**:
  ros__parameters:
    n_ctx: 2048
    n_batch: 1024
    n_predict: 2048
    n_gpu_layers: 0
    cpu:
      n_threads: 1
    embedding: true
    model:
      repo: CompendiumLabs/bge-base-en-v1.5-gguf
      filename: bge-base-en-v1.5-f16.gguf
