/**:
  ros__parameters:
    n_ctx: 2048
    n_batch: 256
    n_predict: -1
    n_gpu_layers: 27
    cpu:
      n_threads: -1
    model:
      repo: vinimuchulski/gemma-3-1b-it-qat-q4_0-gguf
      filename: gemma-3-1b-it-q4_0.gguf
    system_prompt_type: Gemma-3
