/**:
  ros__parameters:
    n_ctx: 2048
    n_batch: 256
    n_gpu_layers: 27
    n_threads: -1
    n_predict: -1
    model_repo: vinimuchulski/gemma-3-1b-it-qat-q4_0-gguf
    model_filename: gemma-3-1b-it-q4_0.gguf
    system_prompt_type: Gemma-3
