/**:
  ros__parameters:
    n_ctx: 2048
    n_batch: 8
    n_gpu_layers: 0
    n_threads: 1
    n_predict: 2048
    model_repo: gorilla-llm/gorilla-openfunctions-v2-gguf
    model_filename: gorilla-openfunctions-v2-q4_K_M.gguf
    system_prompt_type: gorilla
