/**:
  ros__parameters:
    n_ctx: 2048
    n_batch: 8
    n_predict: 2048
    n_gpu_layers: 0
    cpu:
      n_threads: 1
    model:
      repo: QuantFactory/Hermes-2-Theta-Llama-3-8B-GGUF
      filename: Hermes-2-Theta-Llama-3-8B.Q4_K_M.gguf
    system_prompt_type: ChatML
