/**:
  ros__parameters:
    n_ctx: 8192
    n_batch: 256
    n_gpu_layers: 33
    n_threads: -1
    n_predict: 8192
    model_repo: mradermacher/InternVL3-8B-GGUF
    model_filename: InternVL3-8B.Q4_K_M.gguf
    mmproj_repo: mradermacher/InternVL3-8B-GGUF
    mmproj_filename: InternVL3-8B.mmproj-Q8_0.gguf
    system_prompt_type: ChatML
