/**:
  ros__parameters:
    n_ctx: 2048
    n_batch: 1024
    n_predict: 2048
    n_gpu_layers: 0
    cpu:
      n_threads: 1
    reranking: true
    model:
      repo: gpustack/jina-reranker-v1-tiny-en-GGUF
      filename: jina-reranker-v1-tiny-en-FP16.gguf
