/**:
  ros__parameters:
    # Model parameters
    model:
      repo: gpustack/jina-reranker-v1-tiny-en-GGUF
      filename: jina-reranker-v1-tiny-en-FP16.gguf

    # Context / inference parameters
    context:
      n_ctx: 2048
      n_batch: 1024
      n_predict: 2048
      reranking: true

    # GPU / backend parameters
    gpu:
      n_gpu_layers: 0

    # CPU parameters
    cpu:
      n_threads: 1
