/**:
  ros__parameters:
    n_ctx: 8192
    n_batch: 512
    n_predict: 8192
    n_gpu_layers: 33
    cpu:
      n_threads: -1
    model:
      repo: cjpais/llava-1.6-mistral-7b-gguf
      filename: llava-v1.6-mistral-7b.Q4_K_M.gguf
    mmproj:
      repo: cjpais/llava-1.6-mistral-7b-gguf
      filename: mmproj-model-f16.gguf
    system_prompt_type: Mistral
