/**:
  ros__parameters:
    # Model parameters
    model:
      repo: cjpais/llava-1.6-mistral-7b-gguf
      filename: llava-v1.6-mistral-7b.Q4_K_M.gguf

    # Multimodal projector parameters
    mmproj:
      repo: cjpais/llava-1.6-mistral-7b-gguf
      filename: mmproj-model-f16.gguf

    # Context / inference parameters
    context:
      n_ctx: 8192
      n_batch: 512
      n_predict: 8192

    # GPU / backend parameters
    gpu:
      n_gpu_layers: 33

    # CPU parameters
    cpu:
      n_threads: -1

    # Prompt & chat parameters
    prompt:
      system_prompt_type: Mistral
