/**:
  ros__parameters:
    n_ctx: 8192
    n_batch: 512
    n_predict: 8192
    n_gpu_layers: 33
    cpu:
      n_threads: -1
    model:
      repo: xtuner/llava-phi-3-mini-gguf
      filename: llava-phi-3-mini-int4.gguf
    mmproj:
      repo: xtuner/llava-phi-3-mini-gguf
      filename: llava-phi-3-mini-mmproj-f16.gguf
    system_prompt_type: Phi-3
