/**:
  ros__parameters:
    n_ctx: 2048
    n_batch: 8
    n_predict: 2048
    n_gpu_layers: 0
    cpu:
      n_threads: 1
    model:
      repo: TheBloke/Marcoroni-7B-v3-GGUF
      filename: marcoroni-7b-v3.Q4_K_M.gguf
    system_prompt_type: Alpaca
