/**:
  ros__parameters:
    # Model parameters
    model:
      repo: openbmb/MiniCPM-Llama3-V-2_5-gguf
      filename: ggml-model-Q4_K_M.gguf

    # Multimodal projector parameters
    mmproj:
      repo: openbmb/MiniCPM-Llama3-V-2_5-gguf
      filename: mmproj-model-f16.gguf

    # Context / inference parameters
    context:
      n_ctx: 8192
      n_batch: 512
      n_predict: 8192

    # GPU / backend parameters
    gpu:
      n_gpu_layers: 20

    # CPU parameters
    cpu:
      n_threads: -1

    # Prompt & chat parameters
    prompt:
      system_prompt_type: Llama-3
