/**:
  ros__parameters:
    n_ctx: 2048
    n_batch: 8
    n_predict: 2048
    n_gpu_layers: 0
    cpu:
      n_threads: 1
    model:
      repo: bartowski/Ministral-8B-Instruct-2410-GGUF
      filename: Ministral-8B-Instruct-2410-Q4_K_M.gguf
    system_prompt_type: Mistral
