/**:
  ros__parameters:
    n_ctx: 2048
    n_batch: 1024
    n_gpu_layers: 0
    n_threads: -1
    n_predict: 2048
    embedding: true
    model_repo: mixedbread-ai/mxbai-embed-large-v1
    model_filename: gguf/mxbai-embed-large-v1-f16.gguf
