/**:
  ros__parameters:
    n_ctx: 8192
    n_batch: 512
    n_predict: 8192
    n_gpu_layers: -1
    cpu:
      n_threads: -1
    model:
      repo: bartowski/Qwen2-VL-2B-Instruct-GGUF
      filename: Qwen2-VL-2B-Instruct-Q4_K_M.gguf
    mmproj:
      repo: bartowski/Qwen2-VL-2B-Instruct-GGUF
      filename: mmproj-Qwen2-VL-2B-Instruct-f16.gguf
    system_prompt_type: ChatML
