/**:
  ros__parameters:
    # Model parameters
    model:
      repo: bartowski/Qwen2-VL-2B-Instruct-GGUF
      filename: Qwen2-VL-2B-Instruct-Q4_K_M.gguf

    # Multimodal projector parameters
    mmproj:
      repo: bartowski/Qwen2-VL-2B-Instruct-GGUF
      filename: mmproj-Qwen2-VL-2B-Instruct-f16.gguf

    # Context / inference parameters
    context:
      n_ctx: 8192
      n_batch: 512
      n_predict: 8192

    # GPU / backend parameters
    gpu:
      n_gpu_layers: -1

    # CPU parameters
    cpu:
      n_threads: -1

    # Prompt & chat parameters
    prompt:
      system_prompt_type: ChatML
