/**:
  ros__parameters:
    # Model parameters
    model:
      repo: cstr/Spaetzle-v60-7b-GGUF
      filename: Spaetzle-v60-7b-q4-k-m.gguf

    # Context / inference parameters
    context:
      n_ctx: 2048
      n_batch: 8
      n_predict: 2048

    # GPU / backend parameters
    gpu:
      n_gpu_layers: 0

    # CPU parameters
    cpu:
      n_threads: 1

    # Prompt & chat parameters
    prompt:
      system_prompt_type: Alpaca
