/**:
  ros__parameters:
    n_ctx: 2048
    n_batch: 8
    n_predict: 2048
    n_gpu_layers: 0
    cpu:
      n_threads: 1
    model:
      repo: cstr/Spaetzle-v60-7b-GGUF
      filename: Spaetzle-v60-7b-q4-k-m.gguf
    system_prompt_type: Alpaca
