var searchData=
[
  ['cache_0',['KV Cache (&lt;span class=&quot;tt&quot;&gt;cache.*&lt;/span&gt;)',['../index.html#autotoc_md29',1,'']]],
  ['cache_20cache_1',['KV Cache (&lt;span class=&quot;tt&quot;&gt;cache.*&lt;/span&gt;)',['../index.html#autotoc_md29',1,'']]],
  ['chain_2',['llama_ros (Chain)',['../index.html#autotoc_md45',1,'']]],
  ['chat_20audio_3',['chat_llama_ros (Chat + Audio)',['../index.html#autotoc_md52',1,'']]],
  ['chat_20audio_20demo_4',['Chat Audio Demo',['../index.html#autotoc_md68',1,'']]],
  ['chat_20completions_5',['Generate Chat Completions',['../index.html#autotoc_md41',1,'']]],
  ['chat_20multi_20audio_20demo_6',['Chat Multi-Audio Demo',['../index.html#autotoc_md69',1,'']]],
  ['chat_20multi_20image_20demo_7',['Chat Multi-Image Demo',['../index.html#autotoc_md65',1,'']]],
  ['chat_20multi_20image_20user_20input_20demo_8',['Chat Multi-Image (User Input) Demo',['../index.html#autotoc_md66',1,'']]],
  ['chat_20prompt_9',['Prompt &amp;amp; Chat (&lt;span class=&quot;tt&quot;&gt;prompt.*&lt;/span&gt;)',['../index.html#autotoc_md32',1,'']]],
  ['chat_20reasoning_20demo_20deepseek_20r1_10',['Chat Reasoning Demo (DeepSeek-R1)',['../index.html#autotoc_md73',1,'']]],
  ['chat_20structured_20output_20demo_11',['Chat Structured Output Demo',['../index.html#autotoc_md70',1,'']]],
  ['chat_20template_20demo_12',['Chat Template Demo',['../index.html#autotoc_md63',1,'']]],
  ['chat_20template_20rag_20reranking_20stream_13',['RAG Demo (LLM + chat template + RAG + Reranking + Stream)',['../index.html#autotoc_md62',1,'']]],
  ['chat_20tools_20demo_14',['Chat Tools Demo',['../index.html#autotoc_md71',1,'']]],
  ['chat_20vlm_15',['chat_llama_ros (Chat + VLM)',['../index.html#autotoc_md51',1,'']]],
  ['chat_5fllama_5fros_20agent_16',['chat_llama_ros (Agent)',['../index.html#autotoc_md56',1,'']]],
  ['chat_5fllama_5fros_20chat_20audio_17',['chat_llama_ros (Chat + Audio)',['../index.html#autotoc_md52',1,'']]],
  ['chat_5fllama_5fros_20chat_20vlm_18',['chat_llama_ros (Chat + VLM)',['../index.html#autotoc_md51',1,'']]],
  ['chat_5fllama_5fros_20reasoning_19',['chat_llama_ros (Reasoning)',['../index.html#autotoc_md55',1,'']]],
  ['chat_5fllama_5fros_20structured_20output_20',['chat_llama_ros (Structured output)',['../index.html#autotoc_md53',1,'']]],
  ['chat_5fllama_5fros_20tools_21',['chat_llama_ros (Tools)',['../index.html#autotoc_md54',1,'']]],
  ['clients_22',['ROS 2 Clients',['../index.html#autotoc_md35',1,'']]],
  ['completions_23',['Generate Chat Completions',['../index.html#autotoc_md41',1,'']]],
  ['config_24',['Config',['../index.html#autotoc_md11',1,'llama_ros (YAML Config)'],['../index.html#autotoc_md15',1,'llava_ros (YAML Config)']]],
  ['config_20model_20shards_25',['llama_ros (YAML Config + model shards)',['../index.html#autotoc_md12',1,'']]],
  ['contents_26',['Table of Contents',['../index.html#autotoc_md1',1,'']]],
  ['context_27',['Context / Inference (&lt;span class=&quot;tt&quot;&gt;context.*&lt;/span&gt;)',['../index.html#autotoc_md21',1,'']]],
  ['context_20inference_20context_28',['Context / Inference (&lt;span class=&quot;tt&quot;&gt;context.*&lt;/span&gt;)',['../index.html#autotoc_md21',1,'']]],
  ['cpu_29',['CPU (&lt;span class=&quot;tt&quot;&gt;cpu.*&lt;/span&gt;)',['../index.html#autotoc_md24',1,'']]],
  ['cpu_20batch_20cpu_5fbatch_30',['CPU Batch (&lt;span class=&quot;tt&quot;&gt;cpu_batch.*&lt;/span&gt;)',['../index.html#autotoc_md25',1,'']]],
  ['cpu_20cpu_31',['CPU (&lt;span class=&quot;tt&quot;&gt;cpu.*&lt;/span&gt;)',['../index.html#autotoc_md24',1,'']]],
  ['cpu_5fbatch_32',['CPU Batch (&lt;span class=&quot;tt&quot;&gt;cpu_batch.*&lt;/span&gt;)',['../index.html#autotoc_md25',1,'']]]
];
