string architecture             # Model architecture name
string description              # Description field
string name                     # Model name
string basename                 # Base name of the model
string size_label               # Label name of the model
string file_type                # File type of GGUF
string license                  # License of the model
string license_link             # Link to the license
string url                      # URL to the model page
string repo_url                 # URL to the model repository
string[] tags                   # Tags of the model
string[] languages              # Languages supported by the model
string quantized_by             # Name of the use that quantized this model
int32 quantization_version      # Quantization version