name: Lyrical Build and Test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 5 * * 1"

jobs:
  lyrical_build_and_test:
    runs-on: ubuntu-latest
    container:
      image: ros:lyrical
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Python dependencies
        run: |
          apt-get update && apt-get install -y python3-pip
          python3 -m pip install --upgrade pip || python3 -m pip install --break-system-packages --ignore-installed --upgrade pip
          pip3 install --break-system-packages --no-cache-dir --ignore-installed -r requirements.txt
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: llama_ros llama_bt llama_cli
          target-ros2-distro: lyrical
          skip-tests: false
          coverage-result: false
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
